'use server'

import { createClient } from '@/lib/supabase/server'
import { createAdminClient } from '@/lib/supabase/admin'
import { trackServer } from '@/lib/analytics-server'
import bcrypt from 'bcryptjs'
import { redirect } from 'next/navigation'

export async function mfaChallengeVerifyAction(formData: FormData) {
  const code = String(formData.get('code') || '').trim()
  if (!code) return { error: 'Code required.' }

  const supabase = await createClient()
  const { data: factors, error: fErr } = await supabase.auth.mfa.listFactors()
  if (fErr) return { error: fErr.message }

  const totp = factors?.totp?.find((f) => f.status === 'verified')
  if (!totp) return { error: 'No verified authenticator on file.' }

  const challenge = await supabase.auth.mfa.challenge({ factorId: totp.id })
  if (challenge.error) return { error: challenge.error.message }

  const verify = await supabase.auth.mfa.verify({
    factorId: totp.id,
    challengeId: challenge.data.id,
    code,
  })
  if (verify.error) {
    // Observability — track failures so loop-recurrence is visible in PostHog.
    const { data: { user } } = await supabase.auth.getUser()
    if (user) {
      await trackServer(user.id, 'mfa_challenge_failed', {
        reason: verify.error.message,
        factor_id: totp.id,
      })
    }
    return { error: verify.error.message }
  }

  // Flush elevated session cookie to the response before redirecting.
  // Without this, the 3xx generated by redirect() can race the Set-Cookie
  // from mfa.verify(), leaving the next request with stale AAL1 cookies →
  // the AAL gate in proxy.ts bounces the user back to /auth/mfa (the loop).
  const { data: { user: verifiedUser } } = await supabase.auth.getUser()
  if (verifiedUser) {
    await trackServer(verifiedUser.id, 'mfa_challenge_verified', {
      factor_id: totp.id,
    })
  }

  redirect('/dashboard')
}

export async function mfaRecoveryAction(formData: FormData) {
  const code = String(formData.get('code') || '').trim().toUpperCase()
  if (!code) return { error: 'Recovery code required.' }

  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { error: 'Session expired.' }

  const admin = createAdminClient()
  const { data: rows, error } = await admin
    .from('mfa_recovery_codes')
    .select('id, code_hash, used_at')
    .eq('user_id', user.id)
    .is('used_at', null)

  if (error) return { error: error.message }
  if (!rows || rows.length === 0) return { error: 'No recovery codes available.' }

  let matchedId: string | null = null
  for (const r of rows) {
    if (await bcrypt.compare(code, r.code_hash)) {
      matchedId = r.id
      break
    }
  }
  if (!matchedId) return { error: 'Invalid recovery code.' }

  await admin
    .from('mfa_recovery_codes')
    .update({ used_at: new Date().toISOString() })
    .eq('id', matchedId)

  // Unenrol all existing TOTP factors so the user is forced to re-enrol.
  const { data: factors } = await supabase.auth.mfa.listFactors()
  for (const f of factors?.totp ?? []) {
    await supabase.auth.mfa.unenroll({ factorId: f.id })
  }

  // Flush the post-unenrol session cookie before redirecting, same reason as
  // mfaChallengeVerifyAction above — prevent a stale-cookie race with redirect().
  await supabase.auth.getUser()

  redirect('/auth/enroll-mfa')
}
