import { createClient } from '@/lib/supabase/server'
import { getCachedTenantSettings } from '@/lib/tenant/getTenantSettings'
import { Card } from '@/components/ui/Card'
import Link from 'next/link'
import { formatDate } from '@/lib/utils/format'
import { firstRow } from '@/lib/db/relation'
import { SiteMapDynamic } from './SiteMapDynamic'
import type { MapSite } from './SiteMapLeaflet'
import type { Role } from '@/lib/types'
import { DashboardViewToggle } from './DashboardViewToggle'
import { DashboardAnalytics } from './DashboardAnalytics'
import { StatusBadge } from '@/components/ui/StatusBadge'
import { ServiceCreditWidget } from './ServiceCreditWidget'
import { SetupChecklist } from './SetupChecklist'
import { SetupProgressChip } from './SetupProgressChip'
import { TechDashboard } from './TechDashboard'

type View = 'mine' | 'all'

export default async function DashboardPage({
  searchParams,
}: {
  searchParams: Promise<{ view?: string; setup?: string }>
}) {
  const params = await searchParams
  const supabase = await createClient()

  // ── Resolve user, role, profile ──
  const { data: { user } } = await supabase.auth.getUser()
  let userName = 'there'
  let userRole: Role = 'read_only'
  let userId: string | null = null

  let tenantId: string | null = null
  // Welcome-card gate (PR I): null = welcome shown; non-null = dismissed.
  // Only meaningful when userRole === 'technician'.
  let techOnboardedAt: string | null = null
  // Admin setup-checklist dismissal (migration 0104). Null = checklist
  // still shown; non-null = render the SetupProgressChip above the
  // normal dashboard instead. Only meaningful for super_admin / admin.
  let setupChecklistDismissedAt: string | null = null
  if (user) {
    userId = user.id
    const [{ data: profile }, { data: membership }] = await Promise.all([
      supabase.from('profiles').select('full_name').eq('id', user.id).maybeSingle(),
      supabase
        .from('tenant_members')
        // tech_onboarded_at (migration 0102) and setup_checklist_dismissed_at
        // (migration 0104) aren't in the autogenerated database.types.ts yet,
        // so we cast on read. Once db types regenerate the cast can go.
        .select('role, tenant_id, tech_onboarded_at, setup_checklist_dismissed_at' as 'role, tenant_id')
        .eq('user_id', user.id)
        .eq('is_active', true)
        .limit(1)
        .maybeSingle(),
    ])
    userName = profile?.full_name?.split(' ')[0] ?? 'there'
    const memberRow = membership as {
      role?: string
      tenant_id?: string
      tech_onboarded_at?: string | null
      setup_checklist_dismissed_at?: string | null
    } | null
    userRole = (memberRow?.role as Role) ?? 'read_only'
    tenantId = memberRow?.tenant_id ?? null
    techOnboardedAt = memberRow?.tech_onboarded_at ?? null
    setupChecklistDismissedAt = memberRow?.setup_checklist_dismissed_at ?? null
  }

  // Commercial-features flag — gates the service-credit widget. Read via
  // the cached helper so repeated dashboard renders inside the cache TTL
  // skip the Supabase round-trip entirely.
  let commercialEnabled = false
  if (tenantId) {
    const settings = await getCachedTenantSettings(tenantId)
    commercialEnabled = Boolean(settings?.commercial_features_enabled)
  }

  // ── Determine effective view based on role + param ──
  const canToggle = userRole !== 'technician' && userRole !== 'read_only'
  const defaultView: View = userRole === 'super_admin' || userRole === 'admin' ? 'all' : 'mine'
  const effectiveView: View = canToggle && (params.view === 'mine' || params.view === 'all')
    ? params.view
    : canToggle
      ? defaultView
      : 'mine'

  const filterByUser = effectiveView === 'mine' && userId

  // ── Fetch all data in parallel ──
  //
  // 5 parallel calls now (was 16 before migration 0100):
  //   1× get_dashboard_counts RPC — entity + check + defect counts in one trip
  //   3× list queries (upcoming, recent, sites for map) — shapes differ from counts
  //   0× user-filtered count queries — folded into the RPC's optional p_user_id
  //
  // The RPC enforces tenant isolation by parameter (the caller has already
  // verified tenant_id via the membership lookup above). When filterByUser
  // is on, the RPC applies assigned_to/raised_by filters at the SQL layer.
  if (!tenantId) {
    // No tenant context = no useful dashboard. Render with zeros.
  }
  // RPC signature expects string | undefined; use undefined (not null) when
  // we want the tenant-wide path (no user filter).
  const countsUserId = filterByUser && userId ? userId : undefined
  const [
    countsRes,
    tenantRes,
    jobPlanItemsRes,
    upcomingChecks, recentChecks,
    sitesForMap,
  ] = await Promise.all([
    tenantId
      ? supabase.rpc('get_dashboard_counts', { p_tenant_id: tenantId, p_user_id: countsUserId })
      : Promise.resolve({ data: null }),
    // Company-details state: read tenant_settings.report_company_name (the
    // canonical company-name field used in customer reports). Was previously
    // gated on `tenants.setup_completed_at`, which the skipOnboarding action
    // stamps even when no real company data is entered — caused the checklist
    // to falsely tick "Company details done" (UX audit PR #149 §2.2).
    tenantId
      ? supabase.from('tenant_settings').select('report_company_name').eq('tenant_id', tenantId).maybeSingle()
      : Promise.resolve({ data: null }),
    // Job-plan-with-items state: a plan with zero items spawns empty per-asset
    // task lists when a check is created against it — silent failure surfaced
    // by the audit (§A.3 / §2.3). The checklist now gates "Job plan done" on
    // at least one active item existing, not just plan-count > 0.
    tenantId
      ? supabase
          .from('job_plan_items')
          .select('id', { count: 'exact', head: true })
          .eq('tenant_id', tenantId)
      : Promise.resolve({ count: 0 }),
    // Upcoming checks
    buildListQuery(
      supabase.from('maintenance_checks')
        .select('id, custom_name, status, due_date, sites(name)')
        .eq('is_active', true)
        .in('status', ['scheduled', 'in_progress', 'overdue'])
        .order('due_date', { ascending: true })
        .limit(8),
      filterByUser, userId,
    ),
    // Recently completed
    buildListQuery(
      supabase.from('maintenance_checks')
        .select('id, custom_name, status, completed_at, sites(name)')
        .eq('is_active', true)
        .eq('status', 'complete')
        .order('completed_at', { ascending: false })
        .limit(6),
      filterByUser, userId,
    ),
    // Sites for map — always tenant-wide
    supabase.from('sites')
      .select('id, name, state, city, latitude, longitude, customer_id, customers(name)')
      .eq('is_active', true),
  ])

  // Unpack the RPC payload. Empty fallback so the rest of the page can
  // render even if the call failed or the user has no tenant.
  type DashboardCounts = {
    entities: { customers: number; sites: number; assets: number; job_plans: number }
    checks:   { scheduled: number; in_progress: number; overdue: number; complete: number }
    defects:  { total: number; critical: number; high: number; medium: number; low: number }
  }
  const counts = (countsRes.data ?? {
    entities: { customers: 0, sites: 0, assets: 0, job_plans: 0 },
    checks:   { scheduled: 0, in_progress: 0, overdue: 0, complete: 0 },
    defects:  { total: 0, critical: 0, high: 0, medium: 0, low: 0 },
  }) as DashboardCounts

  // ── Setup-state swap ──
  // For admins of a tenant that hasn't completed a single maintenance check
  // yet, the dashboard is in "setup mode". The full SetupChecklist replaces
  // the dashboard unless the admin has dismissed it (migration 0104) — once
  // dismissed, the normal dashboard renders with a thin SetupProgressChip
  // pinned above it. The chip deep-links to `?setup=show` which force-shows
  // the full checklist again without clearing the dismissal column.
  //
  // As soon as one check is marked complete, hasAnyCompletedCheck flips true
  // and both the checklist and the chip disappear — the dashboard goes back
  // to its normal life.
  //
  // Technicians and read_only users never see either surface; they're not
  // the audience for tenant setup.
  const isSetupRole = userRole === 'super_admin' || userRole === 'admin'
  const hasAnyCompletedCheck = counts.checks.complete > 0
  const inSetupMode = isSetupRole && !hasAnyCompletedCheck
  const forceShowChecklist = params.setup === 'show'

  // Pre-compute the checklist inputs whenever we're in setup mode — we
  // need them for both the full SetupChecklist render path AND for the
  // SetupProgressChip's "N / 7 complete" label.
  let checklistCompleted = 0
  let checklistTotal = 0
  let companyConfigured = false
  let hasJobPlanWithItems = false
  if (inSetupMode) {
    const settingsRow = (tenantRes.data ?? null) as { report_company_name: string | null } | null
    companyConfigured = Boolean(settingsRow?.report_company_name?.trim())
    hasJobPlanWithItems = (jobPlanItemsRes as { count?: number | null })?.count != null
      && (jobPlanItemsRes as { count: number }).count > 0
    // Step-derivation logic must stay in sync with SetupChecklist.tsx —
    // both surfaces have to agree on what "done" means or the chip count
    // drifts from the actual checklist.
    const done = [
      companyConfigured,
      counts.entities.customers > 0,
      counts.entities.sites > 0,
      counts.entities.assets > 0,
      hasJobPlanWithItems,
      counts.checks.scheduled + counts.checks.in_progress + counts.checks.overdue + counts.checks.complete > 0,
      counts.checks.complete > 0,
    ]
    checklistCompleted = done.filter(Boolean).length
    checklistTotal = done.length
  }

  const showFullChecklist = inSetupMode && (!setupChecklistDismissedAt || forceShowChecklist)
  if (showFullChecklist) {
    return (
      <SetupChecklist
        counts={{ entities: counts.entities, checks: counts.checks }}
        userName={userName}
        companyConfigured={companyConfigured}
        hasJobPlanWithItems={hasJobPlanWithItems}
        forcedShow={forceShowChecklist && Boolean(setupChecklistDismissedAt)}
      />
    )
  }

  // ── My in-progress tests (ACB + NSX) — only when view=mine ──
  type TestRow = { id: string; test_date: string; overall_result: string; assets: { name: string } | { name: string }[] | null; sites: { name: string } | { name: string }[] | null }
  let myAcbTests: TestRow[] = []
  let myNsxTests: TestRow[] = []

  if (filterByUser) {
    const [acbRes, nsxRes] = await Promise.all([
      supabase
        .from('acb_tests')
        .select('id, test_date, overall_result, assets(name), sites(name)')
        .eq('tested_by', userId!)
        .eq('is_active', true)
        .neq('overall_result', 'Pass')
        .order('test_date', { ascending: false })
        .limit(6),
      supabase
        .from('nsx_tests')
        .select('id, test_date, overall_result, assets(name), sites(name)')
        .eq('tested_by', userId!)
        .eq('is_active', true)
        .neq('overall_result', 'Pass')
        .order('test_date', { ascending: false })
        .limit(6),
    ])
    myAcbTests = (acbRes.data ?? []) as unknown as TestRow[]
    myNsxTests = (nsxRes.data ?? []) as unknown as TestRow[]
  }

  // ── Tech-shaped dashboard ──
  // Technicians get a focused, top-loaded layout (UX audit PR #149 §5.1 +
  // §2.7 — locked 2026-05-18): My Upcoming Works first, Recently
  // Completed second, optional In-Progress Tests, status bar at the
  // bottom. Skips the tenant-wide entity KPIs, defect summary, and
  // site map — those are admin/supervisor surfaces.
  if (userRole === 'technician') {
    return (
      <TechDashboard
        userName={userName}
        greeting={getGreeting()}
        upcomingChecks={(upcomingChecks.data ?? []) as unknown as Parameters<typeof TechDashboard>[0]['upcomingChecks']}
        recentChecks={(recentChecks.data ?? []) as unknown as Parameters<typeof TechDashboard>[0]['recentChecks']}
        myAcbTests={myAcbTests}
        myNsxTests={myNsxTests}
        siteCount={counts.entities.sites}
        checkCounts={{
          scheduled:  counts.checks.scheduled,
          inProgress: counts.checks.in_progress,
          overdue:    counts.checks.overdue,
          complete:   counts.checks.complete,
        }}
        // PR I §B.6 — first-session welcome. Shown until the tech taps
        // dismiss; the action stamps tenant_members.tech_onboarded_at.
        showWelcome={techOnboardedAt === null}
        firstName={userName !== 'there' ? userName : null}
      />
    )
  }

  const entityStats = [
    { label: 'Sites',     value: counts.entities.sites,     href: '/sites',     bgLight: 'bg-sky-50',    textColour: 'text-sky-700' },
    { label: 'Assets',    value: counts.entities.assets,    href: '/assets',    bgLight: 'bg-blue-50',   textColour: 'text-blue-700' },
    { label: 'Maintenance Plans', value: counts.entities.job_plans, href: '/job-plans', bgLight: 'bg-indigo-50', textColour: 'text-indigo-700' },
    { label: 'Customers', value: counts.entities.customers, href: '/customers', bgLight: 'bg-violet-50', textColour: 'text-violet-700' },
  ]

  const checkCounts = {
    scheduled:  counts.checks.scheduled,
    inProgress: counts.checks.in_progress,
    overdue:    counts.checks.overdue,
    complete:   counts.checks.complete,
  }
  const totalActive = checkCounts.scheduled + checkCounts.inProgress + checkCounts.overdue

  const defectCounts = {
    total:    counts.defects.total,
    critical: counts.defects.critical,
    high:     counts.defects.high,
    medium:   counts.defects.medium,
    low:      counts.defects.low,
  }

  // ── Active asset counts per site (for map pins) ──
  const mapSiteIds = (sitesForMap.data ?? []).map((s) => s.id as string)
  const mapCountMap = new Map<string, number>()
  if (mapSiteIds.length > 0) {
    const { data: countRows } = await supabase
      .rpc('get_active_asset_counts_by_site', { p_site_ids: mapSiteIds })
    for (const row of (countRows ?? []) as Array<{ site_id: string; asset_count: number }>) {
      mapCountMap.set(row.site_id, Number(row.asset_count))
    }
  }

  const mapSites: MapSite[] = (sitesForMap.data ?? []).map((site) => {
    const customerName = firstRow(site.customers as { name: string } | { name: string }[] | null)?.name ?? null
    return {
      id: site.id,
      name: site.name,
      state: site.state,
      city: site.city,
      latitude: site.latitude,
      longitude: site.longitude,
      customer_name: customerName,
      asset_count: mapCountMap.get(site.id as string) ?? 0,
    }
  })

  const myTestsTotal = myAcbTests.length + myNsxTests.length

  // Setup chip — only shown for admins in setup mode who dismissed the
  // full checklist. The chip vanishes the moment any maintenance check
  // completes (carried by `inSetupMode`).
  const showSetupChip = inSetupMode && Boolean(setupChecklistDismissedAt)

  return (
    <div className="space-y-6">
      {/* Analytics: dashboard_viewed (fires once per mount, client-side) */}
      <DashboardAnalytics siteCount={counts.entities.sites} openChecksCount={totalActive} />

      {showSetupChip && (
        <SetupProgressChip completed={checklistCompleted} total={checklistTotal} />
      )}

      {/* Welcome header — view toggle (if available) lives inline in the subtitle,
          not as a separate top-right pill. Keeps the dashboard header clean now
          that the global plan chip has moved into the sidebar footer. */}
      <div>
        <h1 className="text-2xl font-bold text-eq-ink">Good {getGreeting()}, {userName}</h1>
        <p className="text-sm text-eq-grey mt-1">
          {effectiveView === 'mine'
            ? totalActive > 0
              ? `You have ${totalActive} active ${totalActive === 1 ? 'check' : 'checks'} assigned to you.`
              : 'You have no active checks assigned.'
            : totalActive > 0
              ? `${totalActive} active maintenance ${totalActive === 1 ? 'check' : 'checks'} across all sites.`
              : 'All maintenance checks are up to date.'
          }
          {canToggle && (
            <>
              {' · '}
              <DashboardViewToggle currentView={effectiveView} />
            </>
          )}
        </p>
      </div>

      {/* Overdue alert banner */}
      {checkCounts.overdue > 0 && (
        <Link href="/maintenance?status=overdue" className="block">
          <div className="flex items-center gap-3 px-4 py-3 rounded-xl bg-gradient-to-r from-amber-50 to-orange-50 border border-amber-200 hover:border-amber-300 transition-colors">
            <div className="w-10 h-10 rounded-full bg-amber-100 flex items-center justify-center shrink-0">
              <span className="text-lg">⚠️</span>
            </div>
            <div className="flex-1 min-w-0">
              <p className="text-sm font-bold text-amber-800">
                {checkCounts.overdue} overdue {checkCounts.overdue === 1 ? 'check' : 'checks'} need{effectiveView === 'mine' ? ' your' : ''} attention
              </p>
              <p className="text-xs text-amber-600 mt-0.5">Click to view and action overdue maintenance checks</p>
            </div>
            <span className="text-amber-400 text-sm font-medium shrink-0">View →</span>
          </div>
        </Link>
      )}

      {/* Quick KPIs — always tenant-wide */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
        {entityStats.map(({ label, value, href, bgLight, textColour }) => (
          <Link key={label} href={href} className="block group">
            <div className={`${bgLight} rounded-xl p-4 border border-transparent group-hover:border-eq-sky/30 transition-all group-hover:shadow-sm`}>
              <p className="text-xs font-bold text-eq-grey uppercase tracking-wide">{label}</p>
              <p className={`text-3xl font-bold ${textColour} mt-1`}>{value.toLocaleString()}</p>
            </div>
          </Link>
        ))}
      </div>

      {/* My Tests — shown when view=mine and there are in-progress tests */}
      {filterByUser && myTestsTotal > 0 && (
        <Card>
          <div className="flex items-center justify-between mb-3">
            <h2 className="text-sm font-bold text-eq-ink">My In-Progress Tests</h2>
            <Link href="/testing" className="text-xs text-eq-sky hover:text-eq-deep font-medium">View all →</Link>
          </div>
          <div className="space-y-1">
            {[...myAcbTests.map(t => ({ ...t, kind: 'ACB' })), ...myNsxTests.map(t => ({ ...t, kind: 'NSX' }))].map(test => {
              const assetName = firstRow(test.assets as { name: string } | { name: string }[] | null)?.name ?? '—'
              const siteName = firstRow(test.sites as { name: string } | { name: string }[] | null)?.name ?? ''
              const isDefect = test.overall_result === 'Defect'
              const isPending = test.overall_result === 'Pending'
              return (
                <Link
                  key={test.id}
                  href={`/testing/${test.kind.toLowerCase()}`}
                  className="flex items-center justify-between px-3 py-2.5 rounded-lg hover:bg-gray-50 transition-colors border border-transparent hover:border-gray-100"
                >
                  <div className="min-w-0 flex-1">
                    <p className="text-sm font-medium text-eq-ink truncate">{assetName}</p>
                    <p className="text-xs text-eq-grey">{siteName}</p>
                  </div>
                  <div className="flex items-center gap-2 shrink-0 ml-3">
                    <span className="px-2 py-0.5 rounded-full text-[10px] font-bold uppercase bg-gray-100 text-eq-grey">{test.kind}</span>
                    {isDefect && <StatusBadge status="blocked" label="Defect" />}
                    {isPending && <StatusBadge status="not-started" label="Pending" />}
                    <span className="text-xs text-eq-grey">{formatDate(test.test_date)}</span>
                  </div>
                </Link>
              )
            })}
          </div>
        </Card>
      )}

      {/* Maintenance status bar */}
      <Card>
        <div className="flex items-center justify-between mb-3">
          <h2 className="text-sm font-bold text-eq-ink">Maintenance Overview{effectiveView === 'mine' ? ' — My Checks' : ''}</h2>
          <Link href="/maintenance" className="text-xs text-eq-sky hover:text-eq-deep font-medium">View all →</Link>
        </div>
        <div className="grid grid-cols-4 gap-3">
          <Link href="/maintenance?status=scheduled" className="rounded-lg bg-blue-50 p-3 text-center hover:bg-blue-100 transition-colors border border-blue-100">
            <p className="text-2xl font-bold text-eq-deep">{checkCounts.scheduled}</p>
            <p className="text-xs text-eq-grey mt-0.5">Scheduled</p>
          </Link>
          <Link href="/maintenance?status=in_progress" className="rounded-lg bg-sky-50 p-3 text-center hover:bg-sky-100 transition-colors border border-sky-100">
            <p className="text-2xl font-bold text-eq-sky">{checkCounts.inProgress}</p>
            <p className="text-xs text-eq-grey mt-0.5">In Progress</p>
          </Link>
          <Link href="/maintenance?status=overdue" className="rounded-lg bg-amber-50 p-3 text-center hover:bg-amber-100 transition-colors border border-amber-100">
            <p className={`text-2xl font-bold ${checkCounts.overdue > 0 ? 'text-amber-600' : 'text-eq-grey'}`}>{checkCounts.overdue}</p>
            <p className="text-xs text-eq-grey mt-0.5">Overdue</p>
          </Link>
          <Link href="/maintenance?status=complete" className="rounded-lg bg-green-50 p-3 text-center hover:bg-green-100 transition-colors border border-green-100">
            <p className="text-2xl font-bold text-green-600">{checkCounts.complete}</p>
            <p className="text-xs text-eq-grey mt-0.5">Complete</p>
          </Link>
        </div>
      </Card>

      {/* Service-credit risk — Phase 6 of the contract-scope bridge plan.
          Only renders for tenants on the commercial tier; the widget is a
          server component that fetches its own data so the dashboard
          page.tsx stays focused on the always-on KPIs. */}
      {commercialEnabled && tenantId && (
        <ServiceCreditWidget tenantId={tenantId} />
      )}

      {/* Defect Summary + Map — side by side on large screens */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Defect Summary */}
        <Card>
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-sm font-bold text-eq-ink">{effectiveView === 'mine' ? 'My Open Defects' : 'Open Defects'}</h2>
            <span className="text-xs text-eq-grey">{defectCounts.total} total</span>
          </div>
          {defectCounts.total === 0 ? (
            <div className="text-center py-6">
              <div className="w-10 h-10 rounded-full bg-green-50 flex items-center justify-center mx-auto mb-2">
                <span className="text-green-500 text-lg">✓</span>
              </div>
              <p className="text-sm text-eq-grey">{effectiveView === 'mine' ? 'No defects raised by you' : 'No open defects'}</p>
            </div>
          ) : (
            <div className="space-y-3">
              {[
                { label: 'Critical', count: defectCounts.critical, bg: 'bg-red-500', bgLight: 'bg-red-50', text: 'text-red-700' },
                { label: 'High', count: defectCounts.high, bg: 'bg-orange-500', bgLight: 'bg-orange-50', text: 'text-orange-700' },
                { label: 'Medium', count: defectCounts.medium, bg: 'bg-amber-400', bgLight: 'bg-amber-50', text: 'text-amber-700' },
                { label: 'Low', count: defectCounts.low, bg: 'bg-sky-400', bgLight: 'bg-sky-50', text: 'text-sky-700' },
              ].map(({ label, count, bg, bgLight, text }) => (
                <div key={label}>
                  <div className="flex items-center justify-between mb-1">
                    <span className={`text-xs font-medium ${text}`}>{label}</span>
                    <span className={`text-xs font-bold ${text}`}>{count}</span>
                  </div>
                  <div className={`h-2 rounded-full ${bgLight} overflow-hidden`}>
                    <div
                      className={`h-full rounded-full ${bg} transition-all duration-500`}
                      style={{ width: defectCounts.total > 0 ? `${Math.max((count / defectCounts.total) * 100, count > 0 ? 8 : 0)}%` : '0%' }}
                    />
                  </div>
                </div>
              ))}
            </div>
          )}
        </Card>

        {/* Interactive Map — always tenant-wide */}
        <div className="lg:col-span-2">
          <Card>
            <div className="flex items-center justify-between mb-4">
              <h2 className="text-sm font-bold text-eq-ink">Site Locations</h2>
              <Link href="/sites" className="text-xs text-eq-sky hover:text-eq-deep font-medium">View all →</Link>
            </div>
            <SiteMapDynamic sites={mapSites} />
          </Card>
        </div>
      </div>

      {/* Upcoming works + Recently completed — side by side */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Upcoming Works */}
        <Card>
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-sm font-bold text-eq-ink">{effectiveView === 'mine' ? 'My Upcoming Works' : 'Upcoming Works'}</h2>
            <Link href="/maintenance?status=scheduled" className="text-xs text-eq-sky hover:text-eq-deep font-medium">View all →</Link>
          </div>
          {(upcomingChecks.data?.length ?? 0) === 0 ? (
            <p className="text-sm text-eq-grey py-4 text-center">{effectiveView === 'mine' ? 'No checks assigned to you' : 'No upcoming checks'}</p>
          ) : (
            <div className="space-y-1">
              {(upcomingChecks.data ?? []).map((check: { id: string; custom_name: string | null; status: string; due_date: string; sites: unknown }) => {
                const siteName = firstRow(check.sites as { name: string } | { name: string }[] | null)?.name ?? '—'
                const isOverdue = check.status === 'overdue'
                const isActive = check.status === 'in_progress'
                return (
                  <Link key={check.id} href={`/maintenance/${check.id}`}
                    className="flex items-center justify-between px-3 py-2.5 rounded-lg hover:bg-gray-50 transition-colors border border-transparent hover:border-gray-100 group">
                    <div className="min-w-0 flex-1">
                      <p className="text-sm font-medium text-eq-ink truncate">{check.custom_name ?? siteName}</p>
                      <p className="text-xs text-eq-grey">{siteName}</p>
                    </div>
                    <div className="flex items-center gap-2 shrink-0 ml-3">
                      {isOverdue && <StatusBadge status="overdue" />}
                      {isActive && <StatusBadge status="in-progress" label="Active" />}
                      <span className="text-xs text-eq-grey">{formatDate(check.due_date)}</span>
                    </div>
                  </Link>
                )
              })}
            </div>
          )}
        </Card>

        {/* Recently Completed */}
        <Card>
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-sm font-bold text-eq-ink">{effectiveView === 'mine' ? 'My Recently Completed' : 'Recently Completed'}</h2>
            <Link href="/maintenance?status=complete" className="text-xs text-eq-sky hover:text-eq-deep font-medium">View all →</Link>
          </div>
          {(recentChecks.data?.length ?? 0) === 0 ? (
            <p className="text-sm text-eq-grey py-4 text-center">{effectiveView === 'mine' ? 'No completed checks yet' : 'No completed checks yet'}</p>
          ) : (
            <div className="space-y-1">
              {(recentChecks.data ?? []).map((check: { id: string; custom_name: string | null; status: string; completed_at: string; sites: unknown }) => {
                const siteName = firstRow(check.sites as { name: string } | { name: string }[] | null)?.name ?? '—'
                return (
                  <Link key={check.id} href={`/maintenance/${check.id}`}
                    className="flex items-center justify-between px-3 py-2.5 rounded-lg hover:bg-gray-50 transition-colors border border-transparent hover:border-gray-100">
                    <div className="min-w-0 flex-1">
                      <p className="text-sm font-medium text-eq-ink truncate">{check.custom_name ?? siteName}</p>
                      <p className="text-xs text-eq-grey">{siteName}</p>
                    </div>
                    <div className="flex items-center gap-2 shrink-0 ml-3">
                      <StatusBadge status="complete" label="Done" />
                      <span className="text-xs text-eq-grey">{formatDate(check.completed_at)}</span>
                    </div>
                  </Link>
                )
              })}
            </div>
          )}
        </Card>
      </div>
    </div>
  )
}

// ── Helpers ──

function getGreeting(): string {
  const hour = new Date().getUTCHours() + 10 // AEST rough
  if (hour < 12) return 'morning'
  if (hour < 17) return 'afternoon'
  return 'evening'
}

/**
 * Conditionally add `assigned_to` filter for the maintenance_checks LIST
 * queries (upcoming + recent). The COUNT queries are now folded into the
 * get_dashboard_counts RPC which applies the same filter at the SQL layer.
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
function buildListQuery(query: any, filterByUser: string | false | null, userId: string | null) {
  if (filterByUser && userId) return query.eq('assigned_to', userId)
  return query
}
