// AUTO-GENERATED FROM schemas/acb_visual_check_item.schema.json. DO NOT EDIT.
// Generated by scripts/gen-types.mjs. Run `node scripts/gen-types.mjs` to refresh.
// Source of truth: schemas/acb_visual_check_item.schema.json — edit the JSON, regenerate.

/**
 * A single qualitative pass/fail item from the visual inspection step of an ACB test (e.g. 'Earth connections OK', 'Arc chutes intact'). Stored in eq-solves-service inside the shared acb_test_readings table — EQ Intake canonicalises this as a distinct child entity because the semantics (pass/fail with no quantitative value) are different to electrical readings.
 */
export interface ACBVisualCheckItem {
  item_id: string;
  tenant_id: string;
  /**
   * Parent ACB test.
   */
  acb_test_id: string;
  /**
   * What is being inspected (e.g. 'Arc chutes intact', 'Earth connections OK').
   */
  label: string;
  /**
   * Pass/fail/N/A. True = pass, false = fail, null = N/A or not yet checked.
   */
  is_pass: boolean | null;
  sort_order?: number;
  notes?: string | null;
  imported_at?: string | null;
  imported_from?: string | null;
}
