// AUTO-GENERATED FROM schemas/acb_electrical_reading.schema.json. DO NOT EDIT.
// Generated by scripts/gen-types.mjs. Run `node scripts/gen-types.mjs` to refresh.
// Source of truth: schemas/acb_electrical_reading.schema.json — edit the JSON, regenerate.

/**
 * A single quantitative electrical reading from the electrical-test step of an ACB test (e.g. insulation resistance, contact resistance, trip time). Stored in eq-solves-service inside the shared acb_test_readings table — EQ Intake canonicalises this as a distinct child entity because readings carry value + unit + optional pass band, whereas visual checks are bare pass/fail.
 */
export interface ACBElectricalReading {
  reading_id: string;
  tenant_id: string;
  /**
   * Parent ACB test.
   */
  acb_test_id: string;
  /**
   * What is being measured (e.g. 'Insulation Resistance L1-N', 'Contact Resistance Pole 1', 'Trip Time at 5x In').
   */
  label: string;
  /**
   * Recorded reading as text. Kept as text to preserve significant digits and notations like '>2000', '0.45' as the technician entered them.
   */
  value: string;
  /**
   * Unit of measure (e.g. 'MΩ', 'mΩ', 'ms', 'V', 'A').
   */
  unit?: string | null;
  /**
   * Pass/fail evaluation against expected range (set at report-render time, not at storage). Null if no pass criteria configured.
   */
  is_pass?: boolean | null;
  sort_order?: number;
  notes?: string | null;
  imported_at?: string | null;
  imported_from?: string | null;
}
