// AUTO-GENERATED FROM schemas/acb_test.schema.json. DO NOT EDIT.
// Generated by scripts/gen-types.mjs. Run `node scripts/gen-types.mjs` to refresh.
// Source of truth: schemas/acb_test.schema.json — edit the JSON, regenerate.

/**
 * Specialised test record for an Air Circuit Breaker (ACB). One header row per (asset, test_date) with full breaker identification, trip-unit + ratings, protection settings, and accessories — matching the exact Excel test sheet layout used by SKS technicians. Child rows: acb_visual_check_items (qualitative pass/fail) and acb_electrical_readings (quantitative readings).
 */
export interface ACBTest {
  acb_test_id: string;
  tenant_id: string;
  /**
   * The ACB asset being tested.
   */
  asset_id: string;
  site_id: string;
  /**
   * Optional link to the parent maintenance_check this test belongs to.
   */
  check_id?: string | null;
  test_date: string;
  tested_by_user_id?: string | null;
  /**
   * Type of test event.
   */
  test_type: "Initial" | "Routine" | "Special";
  /**
   * Manufacturer brand of the breaker (e.g. Schneider, ABB, Terasaki).
   */
  brand?: string | null;
  /**
   * Breaker series / type (e.g. 'Masterpact NW', 'Emax2 E2.2').
   */
  breaker_type?: string | null;
  /**
   * Display name + location combined (matches the xlsx 'Name/Location' field).
   */
  name_location?: string | null;
  /**
   * Schneider performance class.
   */
  performance_level?: null | "N1" | "H1" | "H2" | "H3" | "L1";
  /**
   * Whether an electronic protection unit is fitted.
   */
  protection_unit_fitted?: boolean | null;
  /**
   * Trip unit model (e.g. 'Micrologic 5.0H').
   */
  trip_unit_model?: string | null;
  /**
   * Rated current In (e.g. '630A'). Stored as text to preserve units.
   */
  current_in?: string | null;
  /**
   * Mounting style.
   */
  fixed_withdrawable?: null | "Fixed" | "Withdrawable";
  /**
   * Legacy 'CB Make' field (often duplicates brand).
   */
  cb_make?: string | null;
  cb_model?: string | null;
  cb_serial?: string | null;
  /**
   * Frame rating (e.g. '1600A').
   */
  cb_rating?: string | null;
  /**
   * Number of poles ('3P', '4P').
   */
  cb_poles?: string | null;
  /**
   * Legacy free-text trip unit description.
   */
  trip_unit?: string | null;
  /**
   * Long-time pickup setting Ir.
   */
  trip_settings_ir?: string | null;
  /**
   * Short-time pickup setting Isd.
   */
  trip_settings_isd?: string | null;
  /**
   * Instantaneous pickup setting Ii.
   */
  trip_settings_ii?: string | null;
  /**
   * Earth-fault pickup setting Ig.
   */
  trip_settings_ig?: string | null;
  /**
   * Long-time pickup Ir (matches xlsx layout).
   */
  long_time_ir?: string | null;
  /**
   * Long-time delay tr.
   */
  long_time_delay_tr?: string | null;
  short_time_pickup_isd?: string | null;
  short_time_delay_tsd?: string | null;
  instantaneous_pickup?: string | null;
  earth_fault_pickup?: string | null;
  earth_fault_delay?: string | null;
  earth_leakage_pickup?: string | null;
  earth_leakage_delay?: string | null;
  /**
   * Motor charging accessory voltage/state.
   */
  motor_charge?: string | null;
  /**
   * Shunt trip MX1 voltage/state.
   */
  shunt_trip_mx1?: string | null;
  /**
   * Shunt close XF voltage/state.
   */
  shunt_close_xf?: string | null;
  /**
   * Undervoltage release MN voltage/state.
   */
  undervoltage_mn?: string | null;
  second_shunt_trip?: string | null;
  overall_result: "Pending" | "Pass" | "Fail" | "Defect";
  /**
   * Wizard step 1 (typically asset collection).
   */
  step1_status?: "pending" | "in_progress" | "complete";
  /**
   * Wizard step 2 (typically visual checks).
   */
  step2_status?: "pending" | "in_progress" | "complete";
  /**
   * Wizard step 3 (typically electrical readings).
   */
  step3_status?: "pending" | "in_progress" | "complete";
  active: boolean;
  notes?: string | null;
  imported_at?: string | null;
  imported_from?: string | null;
}
