// AUTO-GENERATED FROM schemas/asset.schema.json. DO NOT EDIT.
// Generated by scripts/gen-types.mjs. Run `node scripts/gen-types.mjs` to refresh.
// Source of truth: schemas/asset.schema.json — edit the JSON, regenerate.

/**
 * A serviceable asset at a site (switchboard, UPS, generator, fire pump, AHU, etc). The atomic unit of EQ Service.
 */
export interface Asset {
  asset_id: string;
  tenant_id: string;
  /**
   * Customer's tag/equipment number. Often physically labelled on the asset.
   */
  external_id?: string | null;
  /**
   * Site this asset belongs to.
   */
  site_id: string;
  /**
   * If this asset is part of a hierarchy (e.g. a breaker inside a switchboard), the parent.
   */
  parent_asset_id?: string | null;
  /**
   * Category of asset. Drives default service schedules and inspection forms.
   */
  asset_type: string;
  /**
   * Display name. Required.
   */
  name: string;
  /**
   * Manufacturer.
   */
  make?: string | null;
  /**
   * Model number / designation.
   */
  model?: string | null;
  serial_number?: string | null;
  /**
   * Capacity/rating as a free text string. e.g. '500kVA', '200A', '1600L/min'.
   */
  rating?: string | null;
  install_date?: string | null;
  warranty_expires?: string | null;
  /**
   * Operational criticality. Drives SLA tier and escalation.
   */
  criticality?: "critical" | "high" | "medium" | "low";
  /**
   * Current physical/operational state of the asset. Distinct from criticality (which measures importance, not state of repair).
   */
  condition?: "good" | "fair" | "poor" | "needs_replacement" | "unknown";
  /**
   * Reference to the service schedule template applied to this asset.
   */
  service_schedule_id?: string | null;
  /**
   * How often this asset is serviced. Free text — common values: '6-Monthly May/Nov', 'Annual', 'Quarterly', 'Monthly', or shorthand like 'M', 'Q', '6M', 'A'. Parsed into a formal service_schedule record at commit time when the schedule entity is the source of truth.
   */
  ppm_frequency?: string | null;
  last_service_date?: string | null;
  next_service_due?: string | null;
  /**
   * Free text location within the site, e.g. 'Level 2 Plant Room', 'MSB-A'.
   */
  location_in_site?: string | null;
  /**
   * Barcode or QR code value for scan-based identification.
   */
  barcode?: string | null;
  active?: boolean;
  /**
   * Short denormalised summary of open issues against this asset. Convenience field for one-glance views — the structured per-defect records live in the asset_defect entity. Example: 'RCD board 2 to be replaced; door hinge bent'.
   */
  defects_summary?: string | null;
  /**
   * Customer-imposed asset taxonomy preserved verbatim. Used when a client requires their own classification scheme on their assets (e.g. data centre operator's Maximo IAM values, principal contractor's compliance taxonomy). Stays as free-form so client-specific structure isn't coerced into our canonical enums.
   */
  client_classification?: {
    [k: string]: unknown;
  } | null;
  notes?: string | null;
  imported_at?: string | null;
  imported_from?: string | null;
}
