// AUTO-GENERATED FROM schemas/asset_defect.schema.json. DO NOT EDIT.
// Generated by scripts/gen-types.mjs. Run `node scripts/gen-types.mjs` to refresh.
// Source of truth: schemas/asset_defect.schema.json — edit the JSON, regenerate.

/**
 * An open issue or fault recorded against an asset. The structured source of truth for asset.defects_summary. One row per defect — lifecycle tracked from raised to resolved.
 */
export interface AssetDefect {
  defect_id: string;
  tenant_id: string;
  /**
   * Source-system defect or work order reference.
   */
  external_id?: string | null;
  /**
   * The asset this defect is raised against.
   */
  asset_id: string;
  /**
   * The service visit during which this defect was identified.
   */
  visit_id?: string | null;
  /**
   * Date the defect was identified and raised.
   */
  raised_date: string;
  /**
   * Staff member who identified and raised the defect.
   */
  raised_by_id?: string | null;
  /**
   * How urgent is the defect? Critical = immediate safety risk or service impact. High = resolve within days. Medium = next scheduled visit. Low = monitor or next annual.
   */
  severity: "critical" | "high" | "medium" | "low";
  /**
   * What is the defect? Plain English description of what was found.
   */
  description: string;
  /**
   * Current lifecycle state of the defect.
   */
  status?: "open" | "in_progress" | "resolved" | "deferred" | "no_action";
  /**
   * Date the defect was resolved, closed, or deferred.
   */
  resolution_date?: string | null;
  /**
   * Staff member who resolved the defect.
   */
  resolved_by_id?: string | null;
  /**
   * What was done to resolve the defect. Required when status = resolved.
   */
  resolution_notes?: string | null;
  /**
   * Estimated cost to rectify (AUD, ex-GST).
   */
  estimated_cost?: number | null;
  /**
   * Actual cost to rectify (AUD, ex-GST).
   */
  actual_cost?: number | null;
  /**
   * File reference URLs for photos of the defect.
   */
  photo_attachments?: {
    url?: string;
    filename?: string | null;
    caption?: string | null;
  }[];
  imported_at?: string | null;
  imported_from?: string | null;
}
