// AUTO-GENERATED FROM schemas/attachment.schema.json. DO NOT EDIT.
// Generated by scripts/gen-types.mjs. Run `node scripts/gen-types.mjs` to refresh.
// Source of truth: schemas/attachment.schema.json — edit the JSON, regenerate.

/**
 * Polymorphic file attachment. One row links a file in Supabase Storage to its parent entity (maintenance_check, asset, test, etc.) via (entity_type, entity_id). EQ Intake imports the metadata row; binary upload happens separately (the storage_path is the address within the 'attachments' bucket).
 */
export interface Attachment {
  attachment_id: string;
  tenant_id: string;
  /**
   * Canonical entity name of the parent (e.g. 'maintenance_check', 'asset', 'acb_test', 'defect'). Matches x-eq-entity on the parent schema.
   */
  entity_type: string;
  /**
   * Primary key of the parent row. Not a hard FK because entity_type is polymorphic — validation is by lookup on the canonical entity.
   */
  entity_id: string;
  /**
   * Original filename as uploaded.
   */
  file_name: string;
  /**
   * File size in bytes.
   */
  file_size?: number;
  /**
   * MIME type.
   */
  content_type?: string;
  /**
   * Path within the 'attachments' Supabase Storage bucket. Conventionally {tenant_id}/{entity_type}/{entity_id}/{file_name}.
   */
  storage_path: string;
  uploaded_by_user_id?: string | null;
  /**
   * Optional categorisation (e.g. 'photo', 'report', 'certificate', 'signature').
   */
  category?: string | null;
  imported_at?: string | null;
  imported_from?: string | null;
}
