// AUTO-GENERATED FROM schemas/check_item.schema.json. DO NOT EDIT.
// Generated by scripts/gen-types.mjs. Run `node scripts/gen-types.mjs` to refresh.
// Source of truth: schemas/check_item.schema.json — edit the JSON, regenerate.

/**
 * The line-item result of a maintenance check: a copy of a maintenance_plan_item with the pass/fail/na result the technician recorded. Equivalent to eq-solves-service's maintenance_check_items table. The plan item's description is snapshotted at check creation so later plan edits don't rewrite history.
 */
export interface CheckItem {
  item_id: string;
  tenant_id: string;
  /**
   * Parent maintenance check.
   */
  check_id: string;
  /**
   * Optional link to the specific (check, asset) row this result belongs to. Lets one check carry per-asset result rows for a single line item.
   */
  check_asset_id?: string | null;
  /**
   * The plan item this row is an instance of. Null if the check was ad-hoc / no plan.
   */
  plan_item_id?: string | null;
  /**
   * Asset this result applies to (denormalised for query speed when check_asset_id is null).
   */
  asset_id?: string | null;
  /**
   * Snapshotted task description at the time of check creation.
   */
  description: string;
  sort_order?: number;
  is_required?: boolean;
  /**
   * Technician's recorded result. Null = not yet checked.
   */
  result?: null | "pass" | "fail" | "na";
  completed_at?: string | null;
  /**
   * Technician who recorded this result.
   */
  completed_by_user_id?: string | null;
  notes?: string | null;
  imported_at?: string | null;
  imported_from?: string | null;
}
