// AUTO-GENERATED FROM schemas/check_asset.schema.json. DO NOT EDIT.
// Generated by scripts/gen-types.mjs. Run `node scripts/gen-types.mjs` to refresh.
// Source of truth: schemas/check_asset.schema.json — edit the JSON, regenerate.

/**
 * Junction row linking a maintenance_check to each asset it covers. One maintenance_check may cover many assets (e.g. an LVACB-A check visits 14 ACBs at SY1). This row carries per-asset Maximo work-order metadata (priority, work_type, target dates, failure codes) and the IR scan result.
 */
export interface CheckAsset {
  check_asset_id: string;
  tenant_id: string;
  /**
   * Parent maintenance check.
   */
  check_id: string;
  /**
   * Asset being checked.
   */
  asset_id: string;
  /**
   * Per-asset status within the check. A check is complete only when all its check_assets are complete or skipped.
   */
  status: "pending" | "in_progress" | "complete" | "skipped" | "failed";
  /**
   * Per-asset WO number when one WO is issued per asset (Delta pattern).
   */
  work_order_number?: string | null;
  /**
   * Maximo work order priority.
   */
  priority?: null | "low" | "medium" | "high" | "urgent";
  /**
   * Maximo work type: PM (preventive), CM (corrective), EM (emergency), CAL (calibration), INSP (inspection).
   */
  work_type?: null | "PM" | "CM" | "EM" | "CAL" | "INSP";
  /**
   * Maximo crew or resource identifier.
   */
  crew_id?: string | null;
  /**
   * Maximo target start date/time.
   */
  target_start?: string | null;
  /**
   * Maximo target completion date/time.
   */
  target_finish?: string | null;
  /**
   * Actual per-asset completion timestamp.
   */
  completed_at?: string | null;
  /**
   * Maximo failure classification code.
   */
  failure_code?: string | null;
  /**
   * Problem statement from the work order.
   */
  problem?: string | null;
  /**
   * Root cause of the failure.
   */
  cause?: string | null;
  /**
   * Remedy or corrective action taken.
   */
  remedy?: string | null;
  /**
   * Maximo asset classification path (e.g. 'ELEC \ TRNSFMR').
   */
  classification?: string | null;
  /**
   * Infrared thermal scan result.
   */
  ir_scan_result?: null | "pass" | "fail" | "na" | "not_done";
  notes?: string | null;
  imported_at?: string | null;
  imported_from?: string | null;
}
