// AUTO-GENERATED FROM schemas/contact.schema.json. DO NOT EDIT.
// Generated by scripts/gen-types.mjs. Run `node scripts/gen-types.mjs` to refresh.
// Source of truth: schemas/contact.schema.json — edit the JSON, regenerate.

/**
 * A person at a customer organisation. One customer can have many contacts (procurement, accounts, project manager, etc.). FK to customer via customer_id.
 */
export interface Contact {
  /**
   * Internal canonical ID. Generated on import if not provided.
   */
  contact_id: string;
  /**
   * Owning tenant. Set automatically by import context.
   */
  tenant_id: string;
  /**
   * Customer this contact belongs to. Resolved by FK match on import.
   */
  customer_id: string;
  /**
   * Source-system contact ID.
   */
  external_id?: string | null;
  /**
   * Source-system Customer ID this contact belongs to. Used at intake to resolve customer_id FK before commit.
   */
  external_customer_id?: string | null;
  /**
   * Denormalised company name from the source. Useful when contact rows arrive without a customer lookup table.
   */
  company_name?: string | null;
  /**
   * Honorific (Mr / Mrs / Dr / etc.).
   */
  salutation?: string | null;
  /**
   * Given name. Required.
   */
  first_name: string;
  /**
   * Family name. Required.
   */
  last_name: string;
  email?: string | null;
  /**
   * Work / office phone. Normalised to E.164.
   */
  work_phone?: string | null;
  mobile_phone?: string | null;
  fax?: string | null;
  /**
   * Job title or role.
   */
  position?: string | null;
  department?: string | null;
  notes?: string | null;
  /**
   * True if this is the customer's preferred contact for quotes.
   */
  is_default_quote_contact?: boolean | null;
  /**
   * True if this is the customer's preferred contact for job paperwork.
   */
  is_default_job_contact?: boolean | null;
  /**
   * True if this is the customer's preferred contact for invoices.
   */
  is_default_invoice_contact?: boolean | null;
  /**
   * True if this is the customer's preferred contact for statements.
   */
  is_default_statement_contact?: boolean | null;
  /**
   * Whether this contact is currently active.
   */
  active?: boolean;
  /**
   * When this record was last touched by an intake. System-managed.
   */
  imported_at?: string | null;
  /**
   * Source of the import. System-managed.
   */
  imported_from?: string | null;
}
