// AUTO-GENERATED FROM schemas/contract_scope.schema.json. DO NOT EDIT.
// Generated by scripts/gen-types.mjs. Run `node scripts/gen-types.mjs` to refresh.
// Source of truth: schemas/contract_scope.schema.json — edit the JSON, regenerate.

/**
 * A line in a customer's commercial scope of work, sourced from a contract sheet (DELTA ELCOM 'SCS' tab or equivalent). Carries the structured commercial information: which job plans are in scope, the asset count covered, per-cycle costs (cycle_costs JSONB), per-year base totals (year_totals JSONB, BEFORE CPI), and when assets fall due (due_years JSONB). Audit flags has_bundled_scope and commercial_gap surface walkthrough-discovered anomalies (e.g. T&T delivered inside a fixed JP price, or non-zero labour with zero annual fee).
 */
export interface ContractScope {
  scope_id: string;
  tenant_id: string;
  /**
   * Customer this scope row belongs to.
   */
  customer_id: string;
  /**
   * Site this scope row covers. Null when the scope applies to all customer sites.
   */
  site_id?: string | null;
  /**
   * Australian FY this scope row applies to (e.g. '2025-2026').
   */
  financial_year: string;
  /**
   * Free-text description of the scope line (preserved from legacy rows). New imports also populate jp_code + structured fields.
   */
  scope_item: string;
  /**
   * Whether this line is included in scope (true) or explicitly excluded (false).
   */
  is_included?: boolean;
  /**
   * Billing model. 'fixed' = priced as part of the contract (JPs, priced Additional Items). 'ad_hoc' = billed per visit, no fixed annual price (e.g. RCD/T&T at SY9).
   */
  billing_basis: "fixed" | "ad_hoc";
  /**
   * Job plan code (mirror of maintenance_plan.code, denormalised for CSV import speed). Used to resolve the maintenance_plan FK at commit time.
   */
  jp_code?: string | null;
  /**
   * Count of assets at this site / customer covered by this scope row.
   */
  asset_qty?: number | null;
  /**
   * Raw free-text intervals as they appear in the source sheet (e.g. 'A; 5', 'M/Q/A', 'Q/A'). Normalisation happens later.
   */
  intervals_text?: string | null;
  /**
   * Per-asset cost at each cycle frequency, read from the JP tab 'Total cost per asset' row. NEVER reconstruct from labour x rate — each JP tab has its own per-frequency formula. Shape: { '1YR': 31.25, '5YR': 562.50, ... }. Keys: 1YR, 2YR, 3YR, 4YR, 5YR, 8YR, 10YR, M, Q, S.
   */
  cycle_costs?: {
    [k: string]: number | null;
  };
  /**
   * Per-year base $ totals from the commercial sheet. BEFORE CPI. Apply CPI at read time using customer.cpi_basis + cpi_rate. Shape: { '2026': 22000, '2027': 11000, '2028': 23000 }.
   */
  year_totals?: {
    [k: string]: number | null;
  };
  /**
   * Per-year asset count due, parsed from the SCS 'Comments' column ('5YR: 14 due in 2026'). Drives the calendar generator. Shape: { '2026': 14, '2027': 3, '2028': 15 }.
   */
  due_years?: {
    [k: string]: number | null;
  };
  /**
   * Per-cycle labour hours per asset. Shape: { 'A': 0.25, '5YR': 4.5 }.
   */
  labour_hours_per_asset?: {
    [k: string]: number | null;
  };
  /**
   * For additional_items rows: $ per asset (e.g. RCD push @ $8.50).
   */
  unit_rate_per_asset?: number | null;
  /**
   * TRUE when this row hides additional work inside its fixed price (e.g. T&T at SY3 delivered for $0 line, costed inside a JP fixed price). Surfaced in year-end deliverables.
   */
  has_bundled_scope?: boolean;
  /**
   * TRUE when JP-tab labour is non-zero but SCS Annual is $0 (e.g. E1.25 ACB at AU sites: 0.25 hrs/yr/asset of labour but $0 priced annual). Elevates to audit-hit register for next-year repricing.
   */
  commercial_gap?: boolean;
  /**
   * Import lifecycle status. 'staged' = pending review; 'committed' = live; 'archived' = superseded.
   */
  status?: "staged" | "committed" | "archived";
  /**
   * Filename of the source xlsx (audit trail).
   */
  source_workbook?: string | null;
  /**
   * Sheet/tab name within the source workbook.
   */
  source_sheet?: string | null;
  /**
   * 1-based row number in the source sheet for audit/reconciliation.
   */
  source_row?: number | null;
  /**
   * Groups rows imported in the same xlsx run.
   */
  source_import_id?: string | null;
  notes?: string | null;
  imported_at?: string | null;
  imported_from?: string | null;
}
