// AUTO-GENERATED FROM schemas/contact.schema.json. DO NOT EDIT.
// Generated by scripts/gen-types.mjs. Run `node scripts/gen-types.mjs` to refresh.
// Source of truth: schemas/contact.schema.json — edit the JSON, regenerate.

/**
 * A named person attached to a customer or a specific site. Replaces eq-solves-service's two parallel tables (customer_contacts, site_contacts) with a single canonical entity where exactly one of customer_id / site_id is set. Site-level contacts are surfaced on site reports; customer-level contacts are surfaced on customer dashboards.
 */
export interface Contact {
  contact_id: string;
  tenant_id: string;
  /**
   * Customer this contact belongs to. Exactly one of customer_id / site_id is set.
   */
  customer_id?: string | null;
  /**
   * Site this contact belongs to. Exactly one of customer_id / site_id is set.
   */
  site_id?: string | null;
  /**
   * Full name of the contact.
   */
  name: string;
  /**
   * Free-text job title or role (e.g. 'Facilities Manager', 'Site Supervisor', 'Procurement').
   */
  role?: string | null;
  email?: string | null;
  /**
   * AU phone, coerced to standard format.
   */
  phone?: string | null;
  /**
   * Whether this is the primary contact for the parent (customer or site). At most one primary per parent.
   */
  is_primary?: boolean;
  /**
   * Whether this contact is still current.
   */
  active: boolean;
  notes?: string | null;
  imported_at?: string | null;
  imported_from?: string | null;
}
