// AUTO-GENERATED FROM schemas/customer.schema.json. DO NOT EDIT.
// Generated by scripts/gen-types.mjs. Run `node scripts/gen-types.mjs` to refresh.
// Source of truth: schemas/customer.schema.json — edit the JSON, regenerate.

/**
 * A business or individual the tenant has any relationship with — leads, prospects, active customers, churned. The CRM-style entity. Contracts, billing terms, and SLAs live on a separate service_contract entity that links here (a customer can have many contracts over time; at most one is active at a time).
 *
 * v2 (2026-05-20): Door C split — the contract-side fields (CPI, payment terms, SLAs, hourly rates, contract_template) moved out to service_contract.schema.json. Identification fields (ABN/ACN/legal name) stay here because they're properties of the entity, not the contract.
 */
export interface Customer {
  /**
   * Internal canonical ID. Generated on import if not provided.
   */
  customer_id: string;
  tenant_id: string;
  /**
   * Customer's own ID in an external system (SimPRO CustomerID, MYOB CardID, etc.). Preserved for round-trip exports.
   */
  external_id?: string | null;
  /**
   * Lifecycle classification. lead = early interest, no contact yet. prospect = engaged, quote in flight. active = under contract (has at least one service_contract with status=active). churned = was a customer, contract ended.
   */
  type?: "lead" | "prospect" | "active" | "churned";
  /**
   * Business / company name. Either company_name OR (first_name + last_name) must be set (cross-field rule customer_has_a_name).
   */
  company_name?: string | null;
  /**
   * Given name for individual customers (sole traders, residential).
   */
  first_name?: string | null;
  /**
   * Surname for individual customers.
   */
  last_name?: string | null;
  /**
   * Optional override for how the customer is shown in UI / reports. Falls back to company_name or full personal name.
   */
  display_name?: string | null;
  /**
   * Short identifier used in schedules and reports (e.g. 'EQX-NAT', 'EQX-HS', 'RHC').
   */
  code?: string | null;
  /**
   * Full legal entity name on registration documents (may differ from display name). Property of the entity, not any specific contract.
   */
  customer_entity_legal_name?: string | null;
  /**
   * Australian Business Number (11 digits, stored as string to preserve formatting).
   */
  customer_entity_abn?: string | null;
  /**
   * Australian Company Number (9 digits, stored as string).
   */
  customer_entity_acn?: string | null;
  /**
   * Primary contact email.
   */
  email?: string | null;
  /**
   * Primary phone. Coerced to AU format where possible.
   */
  phone?: string | null;
  /**
   * Free-text head office / billing address. Site-level addresses live on sites.
   */
  address?: string | null;
  /**
   * Customer logo for report letterheads.
   */
  logo_url?: string | null;
  /**
   * Date this customer entered the CRM (lead create date).
   */
  first_engaged_at?: string | null;
  /**
   * Date the customer became active (first contract signed). Null for leads / prospects.
   */
  became_active_at?: string | null;
  /**
   * Date the customer churned. Null while active.
   */
  churned_at?: string | null;
  /**
   * Whether this customer record is currently active (i.e. not soft-deleted). Distinct from `type=active` which is a lifecycle stage.
   */
  active?: boolean;
  notes?: string | null;
  imported_at?: string | null;
  imported_from?: string | null;
}
