// AUTO-GENERATED FROM schemas/customer.schema.json. DO NOT EDIT.
// Generated by scripts/gen-types.mjs. Run `node scripts/gen-types.mjs` to refresh.
// Source of truth: schemas/customer.schema.json — edit the JSON, regenerate.

/**
 * A client company of a tenant. Top of the hierarchy: customers own sites, sites own assets. A customer in EQ Service is the legal entity SKS bills (e.g. Equinix Australia Pty Ltd, Jemena, Ramsay Health). Contract terms, CPI rules, SLAs, and standing hour allocations live here.
 */
export interface Customer {
  /**
   * Internal canonical ID. Generated on import if not provided.
   */
  customer_id: string;
  /**
   * Owning tenant. Set automatically by import context.
   */
  tenant_id: string;
  /**
   * Customer's own ID in an external system. Preserved for round-trip exports.
   */
  external_id?: string | null;
  /**
   * Display name. Required. Should be the legal entity name when known.
   */
  name: string;
  /**
   * Short identifier used in schedules and reports (e.g. 'EQX-NAT', 'EQX-HS', 'RHC').
   */
  code?: string | null;
  /**
   * Primary billing/contact email.
   */
  email?: string | null;
  /**
   * Primary phone. Coerced to AU format where possible.
   */
  phone?: string | null;
  /**
   * Free-text head office address. Site-level addresses live on sites.
   */
  address?: string | null;
  /**
   * Customer logo for report letterheads.
   */
  logo_url?: string | null;
  /**
   * Full legal entity name on the signed contract (may differ from display name).
   */
  customer_entity_legal_name?: string | null;
  /**
   * Australian Business Number (11 digits, stored as string to preserve formatting).
   */
  customer_entity_abn?: string | null;
  /**
   * Australian Company Number (9 digits, stored as string).
   */
  customer_entity_acn?: string | null;
  /**
   * Which contract template this customer is on. Drives derivation logic for year-fees, CPI, scope-coverage rules.
   */
  contract_template?: null | "au_smca_v1" | "hyperscale_v1" | "jemena_v1" | "generic";
  /**
   * SMCA / Master Services Agreement reference number.
   */
  smca_agreement_number?: string | null;
  /**
   * Schedule agreement reference number (attached to a master agreement).
   */
  schedule_agreement_number?: string | null;
  /**
   * Start date of the current contract term. Used as the Y1 base for CPI calculations.
   */
  contract_term_start?: string | null;
  /**
   * End date of the current contract term (before any renewal options).
   */
  contract_term_end?: string | null;
  /**
   * Free-text renewal option encoding, e.g. '+1+1' (two one-year options).
   */
  contract_options?: string | null;
  /**
   * How often the tenant attends this customer's sites for routine maintenance. Drives the calendar coverage check at xlsx import.
   */
  visit_cadence?: null | "monthly" | "quarterly" | "biannual" | "annual" | "ad_hoc";
  /**
   * How CPI is applied year-over-year. Equinix AU SMCA = simple_on_y1_base (Y_n = Y1*(1+rate*(n-1))) — NOT compound.
   */
  cpi_basis?: null | "simple_on_y1_base" | "compound_annual" | "none";
  /**
   * Annual CPI rate as a decimal fraction (e.g. 0.05 = 5%).
   */
  cpi_rate?: number | null;
  /**
   * Whether contract years align to Australian FY (1 Jul - 30 Jun) or calendar year (1 Jan - 31 Dec, Equinix).
   */
  fiscal_year_basis?: null | "au_fy" | "calendar";
  /**
   * Days from invoice to payment due (e.g. 45 for Equinix Net 45).
   */
  payment_terms_days?: number | null;
  /**
   * Standard business hours rate ($/hr).
   */
  hourly_rate_normal?: number | null;
  /**
   * After-hours rate ($/hr).
   */
  hourly_rate_after_hours?: number | null;
  /**
   * Weekend rate ($/hr).
   */
  hourly_rate_weekend?: number | null;
  /**
   * Public holiday rate ($/hr).
   */
  hourly_rate_public_holiday?: number | null;
  /**
   * Minimum charge in hours for an after-hours call-out.
   */
  min_hours_after_hours?: number | null;
  /**
   * Minimum charge in hours for a weekend call-out.
   */
  min_hours_weekend?: number | null;
  /**
   * Date from which the current hourly rates apply.
   */
  hourly_rate_effective_from?: string | null;
  /**
   * Maximum minutes to acknowledge a reactive call (15 for Equinix Premium).
   */
  sla_response_minutes?: number | null;
  /**
   * Maximum hours to be on-site after a reactive call (2 for Equinix).
   */
  sla_onsite_hours?: number | null;
  /**
   * Maximum hours to fully resolve a reactive call (24 for Equinix).
   */
  sla_resolution_hours?: number | null;
  /**
   * Day of month by which the monthly performance report must be issued (Equinix = 7).
   */
  monthly_report_due_day?: number | null;
  /**
   * Notice required (days) before rescheduling a PM visit. Equinix = 30.
   */
  pm_reschedule_notice_days?: number | null;
  /**
   * Service credit as fraction of annual contract value for PM breach (e.g. 0.03 = 3%).
   */
  service_credit_pm_breach_pct?: number | null;
  /**
   * Service credit as fraction of annual contract value for reactive breach.
   */
  service_credit_reactive_breach_pct?: number | null;
  /**
   * Service credit as fraction of annual contract value for spares breach.
   */
  service_credit_spares_breach_pct?: number | null;
  /**
   * Standing supervisor/planner overhead allocation absorbed into the contract value, NOT scheduled to specific dates. Equinix = 80 hrs/quarter.
   */
  management_hours_per_period?: number | null;
  /**
   * Period that management_hours_per_period covers.
   */
  management_period_basis?: null | "quarterly" | "monthly" | "annual";
  /**
   * Whether this customer is currently active.
   */
  active: boolean;
  notes?: string | null;
  imported_at?: string | null;
  imported_from?: string | null;
}
