// AUTO-GENERATED FROM schemas/defect.schema.json. DO NOT EDIT.
// Generated by scripts/gen-types.mjs. Run `node scripts/gen-types.mjs` to refresh.
// Source of truth: schemas/defect.schema.json — edit the JSON, regenerate.

/**
 * A fault or remedial item raised against an asset, typically during a maintenance check or test. Tracked through to resolution with optional work-order linkage. Defects can be auto-raised by the importer when a check_item or test reading fails.
 */
export interface Defect {
  defect_id: string;
  tenant_id: string;
  /**
   * External reference (e.g. customer's CMMS defect number).
   */
  external_id?: string | null;
  /**
   * Maintenance check the defect was raised from.
   */
  check_id?: string | null;
  /**
   * Specific (check, asset) row the defect was raised against.
   */
  check_asset_id?: string | null;
  asset_id?: string | null;
  site_id?: string | null;
  /**
   * Short summary of the defect.
   */
  title: string;
  /**
   * Detailed description of the fault.
   */
  description?: string | null;
  severity: "low" | "medium" | "high" | "critical";
  status: "open" | "in_progress" | "resolved" | "closed";
  raised_by_user_id?: string | null;
  assigned_to_user_id?: string | null;
  resolved_at?: string | null;
  resolved_by_user_id?: string | null;
  /**
   * What was done to resolve the defect.
   */
  resolution_notes?: string | null;
  /**
   * External work order number raised to action the defect.
   */
  work_order_number?: string | null;
  work_order_date?: string | null;
  notes?: string | null;
  imported_at?: string | null;
  imported_from?: string | null;
}
