// AUTO-GENERATED FROM schemas/incident.schema.json. DO NOT EDIT.
// Generated by scripts/gen-types.mjs. Run `node scripts/gen-types.mjs` to refresh.
// Source of truth: schemas/incident.schema.json — edit the JSON, regenerate.

/**
 * Site incidents: injuries, near-misses, hazards observed, environmental events, property damage. Aligned with WHS notifiable incident requirements.
 */
export interface IncidentReport {
  incident_id: string;
  tenant_id: string;
  external_id?: string | null;
  site_id: string;
  incident_type:
    | "injury"
    | "near_miss"
    | "hazard_observed"
    | "property_damage"
    | "environmental"
    | "security"
    | "first_aid"
    | "medical_treatment"
    | "lost_time_injury"
    | "notifiable"
    | "other";
  severity?: "minor" | "moderate" | "serious" | "critical";
  occurred_at: string;
  reported_at?: string | null;
  reported_by: string;
  reported_by_user_id?: string | null;
  involved_persons?: {
    name: string;
    staff_id?: string | null;
    company?: string | null;
    role: "injured_person" | "witness" | "first_aider" | "supervisor" | "other";
    injury_description?: string | null;
    body_part?: string | null;
  }[];
  /**
   * What happened, in plain language. Required.
   */
  description: string;
  /**
   * What was done immediately after the incident.
   */
  immediate_actions?: string | null;
  /**
   * Identified root cause (after investigation).
   */
  root_cause?: string | null;
  contributing_factors?: string[];
  corrective_actions?: {
    action: string;
    owner?: string | null;
    due_date?: string | null;
    completed_at?: string | null;
    status?: "open" | "in_progress" | "completed" | "verified" | "cancelled";
  }[];
  /**
   * Whether this incident is notifiable under WHS Act (death, serious injury/illness, dangerous incident).
   */
  notifiable_to_regulator?: boolean;
  regulator_notification_ref?: string | null;
  regulator_notified_at?: string | null;
  photo_urls?: string[];
  attachments?: {
    url?: string;
    filename?: string;
    kind?: "photo" | "video" | "document" | "medical" | "witness_statement" | "other";
  }[];
  gps?: {
    lat?: number;
    lng?: number;
  } | null;
  weather_conditions?: string | null;
  status?: "draft" | "submitted" | "under_investigation" | "actions_pending" | "closed" | "reopened";
  source?: "cards_mobile" | "import_spreadsheet" | "capture_pdf" | "capture_photo" | "manual_entry";
  raw_extract?: string | null;
  imported_at?: string | null;
  imported_from?: string | null;
}
