// AUTO-GENERATED FROM schemas/itp.schema.json. DO NOT EDIT.
// Generated by scripts/gen-types.mjs. Run `node scripts/gen-types.mjs` to refresh.
// Source of truth: schemas/itp.schema.json — edit the JSON, regenerate.

/**
 * An ITP record: results of an inspection or test against a specified plan. Common in commissioning, fit-off, and quality assurance.
 */
export interface InspectionAndTestPlanRecord {
  itp_id: string;
  tenant_id: string;
  external_id?: string | null;
  site_id: string;
  /**
   * Specific asset being inspected/tested, if applicable.
   */
  asset_id?: string | null;
  /**
   * Reference to the ITP document/standard being followed (e.g. 'AS/NZS 3000-2018 Part 8 Verification', 'Project ITP-EL-001 Rev B').
   */
  itp_reference: string;
  discipline?:
    | null
    | "electrical"
    | "mechanical"
    | "fire"
    | "hydraulic"
    | "civil"
    | "data"
    | "communications"
    | "controls"
    | "other";
  /**
   * What's covered by this ITP record.
   */
  scope?: string | null;
  /**
   * Each test/inspection point and its result.
   *
   * @minItems 1
   */
  checkpoints: [
    {
      checkpoint_no: string;
      description: string;
      acceptance_criteria?: string | null;
      test_method?: string | null;
      /**
       * Test instrument used (e.g. 'Fluke 1664 FC', 'Megger MIT430').
       */
      instrument?: string | null;
      instrument_serial?: string | null;
      instrument_calibration_date?: string | null;
      expected_value?: string | null;
      measured_value?: string | null;
      units?: string | null;
      result: "pass" | "fail" | "n/a" | "hold" | "witness_required";
      witnessed_by?: string | null;
      comments?: string | null;
      photo_urls?: string[];
    },
    ...{
      checkpoint_no: string;
      description: string;
      acceptance_criteria?: string | null;
      test_method?: string | null;
      /**
       * Test instrument used (e.g. 'Fluke 1664 FC', 'Megger MIT430').
       */
      instrument?: string | null;
      instrument_serial?: string | null;
      instrument_calibration_date?: string | null;
      expected_value?: string | null;
      measured_value?: string | null;
      units?: string | null;
      result: "pass" | "fail" | "n/a" | "hold" | "witness_required";
      witnessed_by?: string | null;
      comments?: string | null;
      photo_urls?: string[];
    }[]
  ];
  /**
   * Overall ITP outcome. Computed from checkpoints but stored for reporting.
   */
  overall_result?: "pass" | "fail" | "partial_pass" | "in_progress";
  performed_by: string;
  performed_by_user_id?: string | null;
  performed_at: string;
  witnessed_by?: string | null;
  client_signature?: {
    name?: string;
    signed_at?: string;
    signature_image_url?: string | null;
  } | null;
  attachments?: {
    url?: string;
    filename?: string;
    kind?: "test_certificate" | "calibration_cert" | "photo" | "drawing" | "other";
  }[];
  /**
   * If any checkpoint failed, NCR records.
   */
  non_conformances?: {
    ncr_no?: string | null;
    checkpoint_no?: string;
    description?: string;
    corrective_action?: string | null;
    rectified_at?: string | null;
  }[];
  status?: "draft" | "submitted" | "client_review" | "accepted" | "rejected" | "ncr_raised" | "closed";
  source?: "cards_mobile" | "import_spreadsheet" | "capture_pdf" | "capture_photo" | "manual_entry";
  raw_extract?: string | null;
  imported_at?: string | null;
  imported_from?: string | null;
}
