// AUTO-GENERATED FROM schemas/jsa.schema.json. DO NOT EDIT.
// Generated by scripts/gen-types.mjs. Run `node scripts/gen-types.mjs` to refresh.
// Source of truth: schemas/jsa.schema.json — edit the JSON, regenerate.

/**
 * A Job Safety Analysis (also called Job Hazard Analysis) — a lighter-weight task-level risk assessment than SWMS. Used for non-high-risk work or as a step within an active SWMS.
 */
export interface JobSafetyAnalysis {
  jsa_id: string;
  tenant_id: string;
  external_id?: string | null;
  site_id: string;
  /**
   * If this JSA is part of work covered by an active SWMS, the parent SWMS reference.
   */
  swms_id?: string | null;
  task_description: string;
  prepared_by: string;
  prepared_by_user_id?: string | null;
  prepared_at: string;
  /**
   * Crew members involved in the task.
   */
  crew?: {
    name: string;
    staff_id?: string | null;
    role_on_task?: string | null;
  }[];
  /**
   * Each work step with its hazards and controls.
   *
   * @minItems 1
   */
  steps: [
    {
      step_no: number;
      step_description: string;
      hazards: {
        hazard: string;
        risk_initial?: "low" | "medium" | "high" | "extreme";
        /**
         * @minItems 1
         */
        controls: [string, ...string[]];
        control_hierarchy?: "elimination" | "substitution" | "isolation" | "engineering" | "administrative" | "ppe";
        risk_residual?: "low" | "medium" | "high" | "extreme";
      }[];
      ppe?: string[];
    },
    ...{
      step_no: number;
      step_description: string;
      hazards: {
        hazard: string;
        risk_initial?: "low" | "medium" | "high" | "extreme";
        /**
         * @minItems 1
         */
        controls: [string, ...string[]];
        control_hierarchy?: "elimination" | "substitution" | "isolation" | "engineering" | "administrative" | "ppe";
        risk_residual?: "low" | "medium" | "high" | "extreme";
      }[];
      ppe?: string[];
    }[]
  ];
  signatures?: {
    name: string;
    staff_id?: string | null;
    signed_at: string;
    signature_image_url?: string | null;
  }[];
  status?: "draft" | "active" | "completed" | "archived";
  source?: "cards_mobile" | "import_spreadsheet" | "capture_pdf" | "capture_photo" | "manual_entry";
  raw_extract?: string | null;
  imported_at?: string | null;
  imported_from?: string | null;
}
