// AUTO-GENERATED FROM schemas/maintenance_plan.schema.json. DO NOT EDIT.
// Generated by scripts/gen-types.mjs. Run `node scripts/gen-types.mjs` to refresh.
// Source of truth: schemas/maintenance_plan.schema.json — edit the JSON, regenerate.

/**
 * A reusable maintenance plan template. Defines what work to do (via maintenance_plan_items) on assets matching a scope. Equivalent to eq-solves-service's job_plans table. Plans can be tenant-global (customer_id + site_id both null), customer-scoped (customer_id set), or site-scoped (site_id set — legacy pattern).
 */
export interface MaintenancePlan {
  plan_id: string;
  tenant_id: string;
  /**
   * External system reference (e.g. Maximo PM number, Delta JP id).
   */
  external_id?: string | null;
  /**
   * When set with site_id null, plan applies to all sites of this customer.
   */
  customer_id?: string | null;
  /**
   * Legacy / site-scoped plans. When null, plan is customer- or tenant-scoped.
   */
  site_id?: string | null;
  /**
   * Job plan code (e.g. 'LVACB', 'E1.25', 'M10.13'). Often combined with a frequency suffix in source documents — e.g. 'LVACB-A' parses to code 'LVACB' + frequency suffix 'A'. The suffix is stripped during import and the frequency is set on the maintenance_check, not on the plan.
   */
  code?: string | null;
  /**
   * Display name (e.g. 'LV ACB Service', 'Annual Switchboard PM').
   */
  name: string;
  /**
   * Free-text classification (e.g. 'electrical', 'mechanical', 'safety').
   */
  type?: string | null;
  /**
   * Long-form description of what the plan covers.
   */
  description?: string | null;
  /**
   * Default frequency for instances of this plan. Often null when the plan covers multiple cycles (frequency lives per-item instead). Source codes use suffixes A/Q/M/S/W/2/3/5/8/10 — see x-eq-enum-aliases.
   */
  frequency?:
    | null
    | "weekly"
    | "monthly"
    | "quarterly"
    | "semi_annual"
    | "annual"
    | "2yr"
    | "3yr"
    | "5yr"
    | "8yr"
    | "10yr"
    | "ad_hoc";
  active: boolean;
  notes?: string | null;
  imported_at?: string | null;
  imported_from?: string | null;
}
