// AUTO-GENERATED FROM schemas/maintenance_check.schema.json. DO NOT EDIT.
// Generated by scripts/gen-types.mjs. Run `node scripts/gen-types.mjs` to refresh.
// Source of truth: schemas/maintenance_check.schema.json — edit the JSON, regenerate.

/**
 * A scheduled execution of a maintenance plan at a site. The unit of work a technician is assigned to. Carries the schedule state (status, due_date, started, completed) and an optional frequency override. Source codes (Delta WO, Maximo) often encode the frequency as a suffix on the plan code (e.g. 'LVACB-A' = LVACB plan, A=annual frequency) — the suffix should be parsed off and stored here on the check.
 */
export interface MaintenanceCheck {
  check_id: string;
  tenant_id: string;
  /**
   * External system reference. For Maximo, use maximo_wo_number instead.
   */
  external_id?: string | null;
  /**
   * Maintenance plan this check executes. Optional — ad-hoc checks may have no plan.
   */
  plan_id?: string | null;
  /**
   * Site this check is at.
   */
  site_id: string;
  /**
   * Technician this check is assigned to. Resolves against staff via the auth user mapping.
   */
  assigned_to_user_id?: string | null;
  /**
   * Workflow state. 'overdue' is derived (due_date < today AND status='scheduled'); imports may pre-set it.
   */
  status: "scheduled" | "in_progress" | "complete" | "overdue" | "cancelled";
  /**
   * When the check is required to be performed by.
   */
  due_date: string;
  /**
   * Planned start date (window opens). Distinct from started_at which is the actual start timestamp.
   */
  start_date?: string | null;
  /**
   * Actual timestamp the technician started work.
   */
  started_at?: string | null;
  /**
   * Actual timestamp the check was closed.
   */
  completed_at?: string | null;
  /**
   * Frequency for this specific check, often parsed from the plan code suffix. Delta/Maximo encode suffixes A/Q/M/S/W/2/3/5/8/10 (e.g. 'LVACB-A' → frequency=annual). Falls back to maintenance_plan.frequency if not set.
   */
  frequency?:
    | null
    | "weekly"
    | "monthly"
    | "quarterly"
    | "semi_annual"
    | "annual"
    | "2yr"
    | "3yr"
    | "5yr"
    | "8yr"
    | "10yr"
    | "ad_hoc";
  /**
   * Whether this check is a dark-site (no live electrical work) visit.
   */
  is_dark_site?: boolean;
  /**
   * Override display name for this specific check (defaults to plan name if null).
   */
  custom_name?: string | null;
  /**
   * Maximo work order number. Often the most stable cross-system ID.
   */
  maximo_wo_number?: string | null;
  /**
   * Maximo PM number (the recurring schedule that generated the WO).
   */
  maximo_pm_number?: string | null;
  notes?: string | null;
  imported_at?: string | null;
  imported_from?: string | null;
}
