// AUTO-GENERATED FROM schemas/maintenance_plan_item.schema.json. DO NOT EDIT.
// Generated by scripts/gen-types.mjs. Run `node scripts/gen-types.mjs` to refresh.
// Source of truth: schemas/maintenance_plan_item.schema.json — edit the JSON, regenerate.

/**
 * A single task line item within a maintenance plan. Equivalent to eq-solves-service's job_plan_items table. Items can carry independent frequency flags (freq_monthly, freq_quarterly, ..., freq_10yr) so a single plan can cover items that recur at different cycles.
 */
export interface MaintenancePlanItem {
  item_id: string;
  tenant_id: string;
  /**
   * Parent maintenance plan.
   */
  plan_id: string;
  /**
   * Optional asset this item targets. When null, the item applies to any asset the plan covers.
   */
  asset_id?: string | null;
  /**
   * External system task identifier (e.g. Maximo task id).
   */
  external_id?: string | null;
  /**
   * The task itself, e.g. 'Check earth connections', 'Record incoming voltage L1-L2'.
   */
  description: string;
  /**
   * Display order within the plan.
   */
  sort_order?: number;
  /**
   * Whether the technician must complete this item before the check can be closed.
   */
  is_required?: boolean;
  /**
   * Item only runs at dark-site visits (no live electrical work).
   */
  dark_site?: boolean;
  /**
   * Runs at monthly cycles. Multiple freq flags may be true.
   */
  freq_monthly?: boolean;
  /**
   * Runs at quarterly cycles.
   */
  freq_quarterly?: boolean;
  /**
   * Runs at semi-annual (6-month) cycles.
   */
  freq_semi_annual?: boolean;
  /**
   * Runs at annual cycles.
   */
  freq_annual?: boolean;
  /**
   * Runs at 2-year cycles.
   */
  freq_2yr?: boolean;
  /**
   * Runs at 3-year cycles.
   */
  freq_3yr?: boolean;
  /**
   * Runs at 5-year cycles.
   */
  freq_5yr?: boolean;
  /**
   * Runs at 8-year cycles.
   */
  freq_8yr?: boolean;
  /**
   * Runs at 10-year cycles.
   */
  freq_10yr?: boolean;
  notes?: string | null;
  imported_at?: string | null;
  imported_from?: string | null;
}
