// AUTO-GENERATED FROM schemas/nsx_test.schema.json. DO NOT EDIT.
// Generated by scripts/gen-types.mjs. Run `node scripts/gen-types.mjs` to refresh.
// Source of truth: schemas/nsx_test.schema.json — edit the JSON, regenerate.

/**
 * Specialised test record for a Moulded Case Circuit Breaker (MCCB) — Schneider NSX range and equivalents. Mirrors the ACB test shape: one header row per (asset, test_date), with child rows for visual checks (nsx_visual_check_items) and electrical readings (nsx_electrical_readings).
 */
export interface NSXTest {
  nsx_test_id: string;
  tenant_id: string;
  asset_id: string;
  site_id: string;
  check_id?: string | null;
  test_date: string;
  tested_by_user_id?: string | null;
  test_type: "Initial" | "Routine" | "Special";
  /**
   * Manufacturer (commonly Schneider for NSX).
   */
  cb_make?: string | null;
  /**
   * Model (e.g. 'NSX250F', 'NSX630N').
   */
  cb_model?: string | null;
  cb_serial?: string | null;
  /**
   * Frame rating (e.g. '250A', '630A').
   */
  cb_rating?: string | null;
  cb_poles?: string | null;
  /**
   * Trip unit (e.g. 'Micrologic 5.2 E', 'TMD', 'MA').
   */
  trip_unit?: string | null;
  overall_result: "Pending" | "Pass" | "Fail" | "Defect";
  active: boolean;
  notes?: string | null;
  imported_at?: string | null;
  imported_from?: string | null;
}
