// AUTO-GENERATED FROM schemas/nsx_visual_check_item.schema.json. DO NOT EDIT.
// Generated by scripts/gen-types.mjs. Run `node scripts/gen-types.mjs` to refresh.
// Source of truth: schemas/nsx_visual_check_item.schema.json — edit the JSON, regenerate.

/**
 * A qualitative pass/fail item from the visual inspection step of an NSX (MCCB) test. Sibling of acb_visual_check_item — same shape, different parent table.
 */
export interface NSXVisualCheckItem {
  item_id: string;
  tenant_id: string;
  nsx_test_id: string;
  label: string;
  is_pass: boolean | null;
  sort_order?: number;
  notes?: string | null;
  imported_at?: string | null;
  imported_from?: string | null;
}
