// AUTO-GENERATED FROM schemas/nsx_electrical_reading.schema.json. DO NOT EDIT.
// Generated by scripts/gen-types.mjs. Run `node scripts/gen-types.mjs` to refresh.
// Source of truth: schemas/nsx_electrical_reading.schema.json — edit the JSON, regenerate.

/**
 * A quantitative electrical reading from the electrical-test step of an NSX (MCCB) test. Sibling of acb_electrical_reading.
 */
export interface NSXElectricalReading {
  reading_id: string;
  tenant_id: string;
  nsx_test_id: string;
  label: string;
  /**
   * Recorded reading as text. Preserves significant digits and notations like '>2000', 'OL'.
   */
  value: string;
  unit?: string | null;
  is_pass?: boolean | null;
  sort_order?: number;
  notes?: string | null;
  imported_at?: string | null;
  imported_from?: string | null;
}
