// AUTO-GENERATED FROM schemas/pm_calendar.schema.json. DO NOT EDIT.
// Generated by scripts/gen-types.mjs. Run `node scripts/gen-types.mjs` to refresh.
// Source of truth: schemas/pm_calendar.schema.json — edit the JSON, regenerate.

/**
 * A scheduled preventative-maintenance task on a cost-tracking calendar. Distinct from maintenance_check: pm_calendar is the planning view (when work will happen, what it costs, who's notified), maintenance_check is the execution. Carries Australian FY quarter, iCal recurrence rule, and notification settings.
 */
export interface PMCalendarEntry {
  entry_id: string;
  tenant_id: string;
  /**
   * Site this entry is at. May be null for cross-site activities (training, supervisor visits).
   */
  site_id?: string | null;
  /**
   * Optional link to the maintenance_check this calendar entry generated (or vice-versa).
   */
  check_id?: string | null;
  /**
   * Display title (e.g. 'SY1 Quarterly LVACB PM').
   */
  title: string;
  /**
   * Free-text location string (in addition to site_id).
   */
  location?: string | null;
  description?: string | null;
  /**
   * Free-text category (e.g. 'Quarterly maintenance', 'Annual', 'Reactive', 'Training').
   */
  category?: string;
  /**
   * Scheduled start.
   */
  start_time: string;
  /**
   * Scheduled end. Null when only start is known.
   */
  end_time?: string | null;
  /**
   * Planned labour hours for this entry.
   */
  hours?: number | null;
  /**
   * Planned $ cost of contractor + materials (excludes labour rate).
   */
  contractor_materials_cost?: number | null;
  /**
   * Australian FY quarter. Q1=Jul-Sep, Q2=Oct-Dec, Q3=Jan-Mar, Q4=Apr-Jun.
   */
  quarter?: null | "Q1" | "Q2" | "Q3" | "Q4";
  /**
   * Australian FY (e.g. '2025-2026').
   */
  financial_year?: string | null;
  /**
   * iCal RRULE for recurrence engine (e.g. 'FREQ=MONTHLY;INTERVAL=6').
   */
  recurrence_rule?: string | null;
  /**
   * Parent entry when this is a generated occurrence.
   */
  recurrence_parent_id?: string | null;
  /**
   * Days before start_time to send email reminders (e.g. [7, 1]).
   */
  reminder_days_before?: number[] | null;
  /**
   * Email addresses to notify.
   */
  notification_recipients?: string[] | null;
  /**
   * Template identifier or custom body.
   */
  email_template?: string | null;
  last_notified_at?: string | null;
  /**
   * Owner of the entry.
   */
  assigned_to_user_id?: string | null;
  status: "scheduled" | "in_progress" | "completed" | "cancelled";
  active: boolean;
  notes?: string | null;
  imported_at?: string | null;
  imported_from?: string | null;
}
