// AUTO-GENERATED FROM schemas/prestart.schema.json. DO NOT EDIT.
// Generated by scripts/gen-types.mjs. Run `node scripts/gen-types.mjs` to refresh.
// Source of truth: schemas/prestart.schema.json — edit the JSON, regenerate.

/**
 * A daily prestart safety check completed before work commences on a site. Captured by EQ Cards (mobile) or imported from existing registers.
 */
export interface PrestartCheck {
  prestart_id: string;
  tenant_id: string;
  site_id: string;
  date: string;
  shift_start?: string | null;
  /**
   * Free text weather conditions (relevant for outdoor work).
   */
  weather?: string | null;
  /**
   * Name of the person completing the prestart.
   */
  completed_by: string;
  completed_by_user_id?: string | null;
  completed_at?: string | null;
  /**
   * Names of crew members on site for this prestart.
   */
  crew_present?: {
    name: string;
    staff_id?: string | null;
    fit_for_work?: boolean;
    fatigue_concerns?: string | null;
  }[];
  /**
   * Checklist of prestart questions and answers.
   */
  responses: {
    question: string;
    category?:
      | null
      | "ppe"
      | "site_conditions"
      | "tools_plant"
      | "isolation"
      | "permits"
      | "emergency"
      | "environment"
      | "other";
    answer: "yes" | "no" | "n/a";
    comment?: string | null;
    photo_urls?: string[];
  }[];
  hazards_identified?: {
    description: string;
    control: string;
    responsible_person?: string | null;
  }[];
  /**
   * SWMS IDs referenced by this prestart.
   */
  swms_referenced?: string[];
  signature_image_url?: string | null;
  gps?: {
    lat?: number;
    lng?: number;
  } | null;
  device_id?: string | null;
  source?: "cards_mobile" | "import_spreadsheet" | "capture_pdf" | "capture_photo" | "manual_entry";
  raw_extract?: string | null;
  imported_at?: string | null;
  imported_from?: string | null;
}
