// AUTO-GENERATED FROM schemas/rcd_test.schema.json. DO NOT EDIT.
// Generated by scripts/gen-types.mjs. Run `node scripts/gen-types.mjs` to refresh.
// Source of truth: schemas/rcd_test.schema.json — edit the JSON, regenerate.

/**
 * Header row per (RCD board asset, visit). Groups all rcd_test_circuits for that board on that day. Maps to one tab in the Jemena multi-tab xlsx RCD report. Sign-off + technician metadata lives here; per-circuit timing values live on rcd_test_circuit.
 */
export interface RCDTest {
  rcd_test_id: string;
  tenant_id: string;
  customer_id?: string | null;
  site_id: string;
  /**
   * The board / distribution panel the RCD circuits live on.
   */
  asset_id: string;
  /**
   * Optional link to the parent maintenance_check (the 6-monthly visit). Null for ad-hoc tests outside the regular cycle.
   */
  check_id?: string | null;
  test_date: string;
  technician_user_id?: string | null;
  /**
   * Snapshot of technician name at test time, in case the user record is later removed or renamed.
   */
  technician_name_snapshot?: string | null;
  /**
   * Short initials (e.g. 'AH') rendered inline on the per-row signature column of the xlsx report.
   */
  technician_initials?: string | null;
  /**
   * URL of the site rep's captured signature image.
   */
  site_signature_url?: string | null;
  /**
   * Name of the site rep who signed off.
   */
  site_rep_name?: string | null;
  /**
   * Free-text record of the test instrument used (e.g. 'Fluke 1654B Tester #1234').
   */
  equipment_used?: string | null;
  status: "draft" | "complete" | "archived";
  active: boolean;
  notes?: string | null;
  imported_at?: string | null;
  imported_from?: string | null;
}
