// AUTO-GENERATED FROM schemas/rcd_test_circuit.schema.json. DO NOT EDIT.
// Generated by scripts/gen-types.mjs. Run `node scripts/gen-types.mjs` to refresh.
// Source of truth: schemas/rcd_test_circuit.schema.json — edit the JSON, regenerate.

/**
 * One row per RCD circuit tested on a board. Belongs to an rcd_test parent (the board + visit). Renders as one row in the Jemena xlsx deliverable. Timing values stored as text to preserve the '' / blank non-trip indicator used by the Jemena template — numeric coercion happens at report-rendering, not storage. Composite uniqueness: (rcd_test_id, section_label, circuit_no) — multi-section boards (e.g. 'Lighting Section' / 'Power Section') can legitimately have the same circuit_no in each section.
 */
export interface RCDTestCircuit {
  circuit_id: string;
  tenant_id: string;
  /**
   * Parent RCD test (board + visit).
   */
  rcd_test_id: string;
  /**
   * Optional sub-section within a board (e.g. 'Lighting Section', 'Power Section'). NULL when the board is not sub-sectioned. Part of the composite uniqueness key — multi-section boards can repeat circuit_no across sections.
   */
  section_label?: string | null;
  /**
   * Circuit identifier as labelled on the board. Stored as text to support non-numeric labels like '3a' or 'L1-7'.
   */
  circuit_no: string;
  /**
   * Trip current rating in mA (Jemena standard = 30 mA).
   */
  normal_trip_current_ma: number;
  /**
   * Trip time at 1×IΔn, 0° phase, expected no trip. Empty/blank when no trip (Jemena convention).
   */
  x1_no_trip_0_ms?: string | null;
  /**
   * Trip time at 1×IΔn, 180° phase, expected no trip.
   */
  x1_no_trip_180_ms?: string | null;
  /**
   * Trip time at 1×IΔn, 0° phase, expected trip.
   */
  x1_trip_0_ms?: string | null;
  /**
   * Trip time at 1×IΔn, 180° phase, expected trip.
   */
  x1_trip_180_ms?: string | null;
  /**
   * Trip time at 5×IΔn, 0° phase (fast trip).
   */
  x5_fast_0_ms?: string | null;
  /**
   * Trip time at 5×IΔn, 180° phase.
   */
  x5_fast_180_ms?: string | null;
  /**
   * Whether the physical test button on the RCD operated correctly.
   */
  trip_test_button_ok: boolean;
  /**
   * Per-circuit Jemena asset ID (e.g. '30248'). Sub-asset semantics — text marker only, not a FK into assets.
   */
  jemena_circuit_asset_id?: string | null;
  /**
   * Free-text: e.g. 'N/A', 'Critical Equipment — do not trip', or description of corrective action on a fail.
   */
  action_taken?: string | null;
  /**
   * When true, the wizard surfaces a guard so the technician doesn't accidentally trip a UPS / ESS feeder.
   */
  is_critical_load?: boolean;
  sort_order?: number;
  imported_at?: string | null;
  imported_from?: string | null;
}
