// AUTO-GENERATED FROM schemas/schedule.schema.json. DO NOT EDIT.
// Generated by scripts/gen-types.mjs. Run `node scripts/gen-types.mjs` to refresh.
// Source of truth: schemas/schedule.schema.json — edit the JSON, regenerate.

/**
 * A planned allocation of a staff member to a site for a given day. The atomic unit of EQ Field scheduling.
 */
export interface ScheduleEntry {
  entry_id: string;
  tenant_id: string;
  staff_id: string;
  site_id: string;
  /**
   * The day this allocation applies to. ISO 8601 (YYYY-MM-DD).
   */
  date: string;
  /**
   * Hours scheduled. Typically 8.0 for full day, but supports half days, double shifts, etc.
   */
  hours_planned: number;
  /**
   * Actual hours worked. Populated from timesheets after the day passes.
   */
  hours_actual?: number | null;
  /**
   * Shift classification. Drives penalty rates.
   */
  shift?: "day" | "evening" | "night" | "weekend" | "afterhours";
  /**
   * What the staff member is doing on this day.
   */
  task?: string | null;
  status?: "planned" | "confirmed" | "in_progress" | "completed" | "cancelled" | "no_show";
  /**
   * If this entry represents leave instead of work, the leave category.
   */
  leave_type?: null | "annual" | "sick" | "personal" | "rdo" | "tafe" | "unpaid" | "public_holiday" | "other";
  notes?: string | null;
  supervisor_id?: string | null;
  imported_at?: string | null;
  imported_from?: string | null;
}
