// AUTO-GENERATED FROM schemas/service_visit.schema.json. DO NOT EDIT.
// Generated by scripts/gen-types.mjs. Run `node scripts/gen-types.mjs` to refresh.
// Source of truth: schemas/service_visit.schema.json — edit the JSON, regenerate.

/**
 * A planned or completed crew visit to a site. Replaces the hand-built monthly SOW + Master Schedule sheets. One visit = one crew day at one site.
 */
export interface ServiceVisit {
  visit_id: string;
  tenant_id: string;
  /**
   * Source-system job or visit reference (e.g. SimPRO job number).
   */
  external_id?: string | null;
  /**
   * Site this visit is at.
   */
  site_id: string;
  /**
   * The day the visit is/was planned. ISO 8601 (YYYY-MM-DD).
   */
  scheduled_date: string;
  /**
   * Date the visit actually occurred. Null until the visit is completed.
   */
  actual_date?: string | null;
  /**
   * Staff member leading the crew on this visit.
   */
  crew_lead_id?: string | null;
  /**
   * Client's own job/work order reference, as printed on their purchase order or scheduling system.
   */
  client_job_code?: string | null;
  /**
   * Current state of the visit.
   */
  status?: "planned" | "in_progress" | "complete" | "cancelled";
  /**
   * Number of assets expected to be serviced on this visit. Used for scheduling and SOW generation.
   */
  expected_assets?: number | null;
  /**
   * Number of electrical circuits (RCDs, breakers) expected to be tested.
   */
  expected_circuits?: number | null;
  /**
   * Access instructions, parking, site contact details, special requirements. Not a service report.
   */
  logistics_notes?: string | null;
  /**
   * The service contract this visit is billed against.
   */
  service_contract_id?: string | null;
  imported_at?: string | null;
  imported_from?: string | null;
}
