// AUTO-GENERATED FROM schemas/service_task_completion.schema.json. DO NOT EDIT.
// Generated by scripts/gen-types.mjs. Run `node scripts/gen-types.mjs` to refresh.
// Source of truth: schemas/service_task_completion.schema.json — edit the JSON, regenerate.

/**
 * A single service task completed during a visit, for one asset. One row per asset × task per visit. Replaces the SOW Asset Schedule tickbox grid.
 */
export interface ServiceTaskCompletion {
  completion_id: string;
  tenant_id: string;
  /**
   * The service visit this task was completed during.
   */
  visit_id: string;
  /**
   * The asset this task was performed on.
   */
  asset_id: string;
  /**
   * The type of service task performed.
   */
  task_type: string;
  /**
   * Whether the task was completed. False = not done / deferred.
   */
  completed?: boolean;
  /**
   * Timestamp when the task was completed.
   */
  completed_at?: string | null;
  /**
   * Staff member who performed this specific task (may differ from crew lead).
   */
  tech_id?: string | null;
  /**
   * Outcome of the task. Distinct from completed — a task can be completed but still fail.
   */
  result?: null | "pass" | "fail" | "partial" | "not_applicable" | "deferred";
  /**
   * Observations, issues found, actions taken.
   */
  notes?: string | null;
  imported_at?: string | null;
  imported_from?: string | null;
}
