// AUTO-GENERATED FROM schemas/service_contract.schema.json. DO NOT EDIT.
// Generated by scripts/gen-types.mjs. Run `node scripts/gen-types.mjs` to refresh.
// Source of truth: schemas/service_contract.schema.json — edit the JSON, regenerate.

/**
 * A signed (or proposed) commercial agreement between a tenant and a customer — the contract under which SKS bills the customer for maintenance work. A customer can have many service_contracts over time (initial 3-year + extensions, or a new contract on renewal); at most one is `status: active` at a time. Contract scopes (contract_scope rows) hang off a specific service_contract, not directly off the customer.
 *
 * Introduced 2026-05-20 in the Door C schema split. The fields here used to live on customer.schema.json v1; they were lifted out so the customer entity could represent the CRM lifecycle (lead → prospect → active → churned) cleanly.
 */
export interface ServiceContract {
  contract_id: string;
  tenant_id: string;
  /**
   * Customer this contract is with.
   */
  customer_id: string;
  /**
   * Customer-side or external system reference (PO number, contract reference).
   */
  external_id?: string | null;
  /**
   * Short label for this contract (e.g. 'Equinix AU SMCA 2024-2026', 'Jemena RCD Program 2024-2027'). Falls back to '{customer.display_name} — {term_start} to {term_end}' if null.
   */
  name?: string | null;
  /**
   * Lifecycle of this specific contract. draft = pre-signature; active = currently billable; expired = ran out, not renewed; superseded = replaced by a newer contract with the same customer; cancelled = terminated early.
   */
  status: "draft" | "active" | "expired" | "superseded" | "cancelled";
  /**
   * Which contract template was used. Drives derivation logic for year-fees, CPI, scope-coverage rules.
   */
  contract_template?: null | "au_smca_v1" | "hyperscale_v1" | "jemena_v1" | "generic";
  /**
   * SMCA / Master Services Agreement reference number.
   */
  smca_agreement_number?: string | null;
  /**
   * Schedule agreement reference number (attached to a master agreement).
   */
  schedule_agreement_number?: string | null;
  /**
   * Start of the contract term. Used as Y1 base for CPI calculations.
   */
  term_start?: string | null;
  /**
   * End of the current contract term (before any renewal options).
   */
  term_end?: string | null;
  /**
   * Free-text renewal option encoding, e.g. '+1+1' (two one-year options).
   */
  options?: string | null;
  /**
   * How often the tenant attends this customer's sites under this contract. Drives the calendar coverage check at xlsx import.
   */
  visit_cadence?: null | "monthly" | "quarterly" | "biannual" | "annual" | "ad_hoc";
  /**
   * How CPI is applied year-over-year. Equinix AU SMCA = simple_on_y1_base (Y_n = Y1*(1+rate*(n-1))) — NOT compound.
   */
  cpi_basis?: null | "simple_on_y1_base" | "compound_annual" | "none";
  /**
   * Annual CPI rate as a decimal fraction (0.05 = 5%).
   */
  cpi_rate?: number | null;
  /**
   * Whether contract years align to Australian FY (1 Jul - 30 Jun) or calendar year (1 Jan - 31 Dec, Equinix).
   */
  fiscal_year_basis?: null | "au_fy" | "calendar";
  /**
   * Days from invoice to payment due (45 = Equinix Net 45).
   */
  payment_terms_days?: number | null;
  /**
   * Standard business-hours rate ($/hr).
   */
  hourly_rate_normal?: number | null;
  /**
   * After-hours rate ($/hr).
   */
  hourly_rate_after_hours?: number | null;
  /**
   * Weekend rate ($/hr).
   */
  hourly_rate_weekend?: number | null;
  /**
   * Public holiday rate ($/hr).
   */
  hourly_rate_public_holiday?: number | null;
  /**
   * Minimum charge in hours for an after-hours call-out.
   */
  min_hours_after_hours?: number | null;
  /**
   * Minimum charge in hours for a weekend call-out.
   */
  min_hours_weekend?: number | null;
  /**
   * Date from which the current hourly rates apply.
   */
  hourly_rate_effective_from?: string | null;
  /**
   * Maximum minutes to acknowledge a reactive call (15 for Equinix Premium).
   */
  sla_response_minutes?: number | null;
  /**
   * Maximum hours to be on-site after a reactive call (2 for Equinix).
   */
  sla_onsite_hours?: number | null;
  /**
   * Maximum hours to fully resolve a reactive call (24 for Equinix).
   */
  sla_resolution_hours?: number | null;
  /**
   * Day of month by which the monthly performance report must be issued (Equinix = 7).
   */
  monthly_report_due_day?: number | null;
  /**
   * Notice required (days) before rescheduling a PM visit. Equinix = 30.
   */
  pm_reschedule_notice_days?: number | null;
  /**
   * Service credit as fraction of annual contract value for PM breach (0.03 = 3%).
   */
  service_credit_pm_breach_pct?: number | null;
  /**
   * Service credit as fraction of annual contract value for reactive breach.
   */
  service_credit_reactive_breach_pct?: number | null;
  /**
   * Service credit as fraction of annual contract value for spares breach.
   */
  service_credit_spares_breach_pct?: number | null;
  /**
   * Standing supervisor/planner overhead allocation absorbed into the contract value (Equinix = 80 hrs/quarter).
   */
  management_hours_per_period?: number | null;
  /**
   * Period that management_hours_per_period covers.
   */
  management_period_basis?: null | "quarterly" | "monthly" | "annual";
  /**
   * Reference to the signed SMCA document in the attachments table.
   */
  smca_doc_attachment_id?: string | null;
  /**
   * Reference to the signed schedule document in the attachments table.
   */
  schedule_doc_attachment_id?: string | null;
  /**
   * When this contract replaces a previous one (renewal), points at the predecessor. Used to build a contract history per customer.
   */
  supersedes_contract_id?: string | null;
  /**
   * Whether this contract record is currently active (i.e. not soft-deleted). Distinct from `status=active` which is a lifecycle stage.
   */
  active?: boolean;
  notes?: string | null;
  imported_at?: string | null;
  imported_from?: string | null;
}
