// AUTO-GENERATED FROM schemas/site.schema.json. DO NOT EDIT.
// Generated by scripts/gen-types.mjs. Run `node scripts/gen-types.mjs` to refresh.
// Source of truth: schemas/site.schema.json — edit the JSON, regenerate.

/**
 * A physical location where work is performed. May be a customer site, a depot, or a project location.
 */
export interface Site {
  /**
   * Internal canonical ID. Generated on import if not provided.
   */
  site_id: string;
  /**
   * Owning tenant. Set automatically by import context.
   */
  tenant_id: string;
  /**
   * Customer's own ID for this site. Preserved for round-trip exports.
   */
  external_id?: string | null;
  /**
   * Display name. Required.
   */
  name: string;
  /**
   * Short identifier used in schedules and reports.
   */
  code?: string | null;
  /**
   * Customer (client company) this site belongs to. Set via FK resolver from client/customer name on import.
   */
  customer_id?: string | null;
  /**
   * DEPRECATED legacy free-text client name. Retained for round-trip on imports from sources that don't carry a stable customer_id. New imports should resolve to customer_id via the FK resolver; this column may be removed in v2.
   */
  client_name?: string | null;
  /**
   * Site classification. Drives scheduling and reporting behaviour.
   */
  site_type?: "customer" | "project" | "depot" | "office" | "other";
  /**
   * Street address line 1.
   */
  address_line_1?: string | null;
  /**
   * Street address line 2.
   */
  address_line_2?: string | null;
  /**
   * Suburb / locality.
   */
  suburb?: string | null;
  /**
   * AU state. Coerced to standard abbreviation (NSW, VIC, QLD, SA, WA, TAS, NT, ACT).
   */
  state?: string | null;
  /**
   * AU postcode (4 digits). Stored as string to preserve leading zeros (NT/ACT).
   */
  postcode?: string | null;
  /**
   * ISO 3166-1 alpha-2 code. Defaults to AU on import if not specified.
   */
  country?: string | null;
  /**
   * Decimal degrees, -90 to 90.
   */
  latitude?: number | null;
  /**
   * Decimal degrees, -180 to 180.
   */
  longitude?: number | null;
  /**
   * Primary on-site contact.
   */
  site_contact_name?: string | null;
  /**
   * Primary on-site contact phone.
   */
  site_contact_phone?: string | null;
  site_contact_email?: string | null;
  /**
   * Whether site induction is required before staff can attend.
   */
  induction_required?: boolean;
  /**
   * Link to induction documentation.
   */
  induction_url?: string | null;
  /**
   * Whether this site is currently active.
   */
  active: boolean;
  notes?: string | null;
  imported_at?: string | null;
  imported_from?: string | null;
}
