// AUTO-GENERATED FROM schemas/staff.schema.json. DO NOT EDIT.
// Generated by scripts/gen-types.mjs. Run `node scripts/gen-types.mjs` to refresh.
// Source of truth: schemas/staff.schema.json — edit the JSON, regenerate.

/**
 * A staff member who can be scheduled to sites. Includes employees, subcontractors, and labour-hire workers.
 */
export interface Staff {
  /**
   * Internal canonical ID. Generated on import if not provided.
   */
  staff_id: string;
  /**
   * Owning tenant. Set automatically by import context.
   */
  tenant_id: string;
  /**
   * Customer's own ID for this staff member (payroll number, HR system ID, etc). Preserved for round-trip exports.
   */
  external_id?: string | null;
  /**
   * Given name. Required.
   */
  first_name: string;
  /**
   * Family name. Required.
   */
  last_name: string;
  /**
   * What the person actually goes by on site. Often a nickname.
   */
  preferred_name?: string | null;
  /**
   * Primary email. Used for invitations and notifications.
   */
  email?: string | null;
  /**
   * Primary mobile. Stored as E.164 where possible (e.g. +61412345678).
   */
  phone?: string | null;
  /**
   * Engagement type. Drives leave entitlements, charge-out treatment, compliance requirements.
   */
  employment_type: "employee" | "subcontractor" | "labour_hire" | "casual" | "apprentice";
  /**
   * Primary trade discipline. Free text but suggested values controlled.
   */
  trade?: string | null;
  /**
   * Trade level / classification.
   */
  level?: string | null;
  /**
   * Date the person started with the business. ISO 8601 (YYYY-MM-DD).
   */
  start_date?: string | null;
  /**
   * Date the person finished (if applicable). Null = currently active.
   */
  end_date?: string | null;
  /**
   * Cost rate per hour (what the business pays). AUD. Sensitive — hidden from non-admin roles.
   */
  hourly_rate_cost?: number | null;
  /**
   * Charge-out rate per hour (what clients are billed). AUD.
   */
  hourly_rate_charge?: number | null;
  /**
   * Where the person typically starts the day. City, suburb, or depot.
   */
  home_base?: string | null;
  /**
   * Site this person is usually at. Resolved by FK match on import.
   */
  default_site_id?: string | null;
  /**
   * Whether this person is currently active. Defaults true on import.
   */
  active: boolean;
  /**
   * Free-form notes. Not used in scheduling logic.
   */
  notes?: string | null;
  /**
   * When this record was last imported. System-managed.
   */
  imported_at?: string | null;
  /**
   * Source of the import (filename, system name). System-managed.
   */
  imported_from?: string | null;
}
