// AUTO-GENERATED FROM schemas/swms.schema.json. DO NOT EDIT.
// Generated by scripts/gen-types.mjs. Run `node scripts/gen-types.mjs` to refresh.
// Source of truth: schemas/swms.schema.json — edit the JSON, regenerate.

/**
 * An SWMS captured for a high-risk construction work activity, per WHS Regulation 2017 (NSW) and equivalents. Lands in this canonical form whether captured via EQ Cards (mobile), EQ Import (existing register), or EQ Capture (paper/PDF).
 */
export interface SafeWorkMethodStatement {
  swms_id: string;
  tenant_id: string;
  /**
   * Customer's own SWMS number/reference.
   */
  external_id?: string | null;
  /**
   * Version string e.g. 'v1.0', 'Rev B'.
   */
  version?: string | null;
  site_id: string;
  /**
   * Short description of the high-risk work activity.
   */
  activity: string;
  /**
   * WHS Reg cl.291 high-risk construction work categories that apply.
   */
  high_risk_categories?: (
    | "fall_above_2m"
    | "telecommunication_tower"
    | "demolition_load_bearing"
    | "asbestos_disturbance"
    | "structural_alterations_temp_support"
    | "confined_space"
    | "trench_excavation_above_1.5m"
    | "tunnels"
    | "explosives"
    | "near_pressurised_gas"
    | "near_chemical_pipelines"
    | "near_energised_electrical"
    | "in_area_traffic_other_than_works"
    | "tilt_up_or_precast"
    | "diving"
    | "near_water_drowning_risk"
    | "movement_of_powered_mobile_plant"
    | "extreme_temperatures"
    | "artificial_extremes_temperature"
  )[];
  /**
   * Identified hazards and controls. Each row = one hazard line.
   */
  hazards?: {
    /**
     * Hazard description.
     */
    hazard: string;
    /**
     * Risk rating before controls.
     */
    risk_initial: "low" | "medium" | "high" | "extreme";
    /**
     * Hierarchy of controls applied (elimination → substitution → engineering → administrative → PPE).
     */
    controls: string[];
    control_hierarchy?: "elimination" | "substitution" | "isolation" | "engineering" | "administrative" | "ppe";
    risk_residual: "low" | "medium" | "high" | "extreme";
    responsible_person?: string | null;
  }[];
  /**
   * PPE list e.g. hard hat, hi-vis, safety glasses, hearing protection, gloves, steel cap boots.
   */
  ppe_required?: string[];
  permits_required?: (
    | "hot_work"
    | "confined_space"
    | "working_at_height"
    | "electrical_isolation"
    | "excavation"
    | "live_electrical"
    | "none"
  )[];
  /**
   * Tools and plant required for the activity.
   */
  tools_plant?: string[];
  /**
   * Training/competency required (e.g. EWP licence, confined space ticket, electrical licence).
   */
  training_competency?: string[];
  /**
   * Site-specific emergency response (assembly point, first aid, who to call).
   */
  emergency_procedures?: string | null;
  prepared_by_user_id?: string | null;
  /**
   * Name of person who prepared the SWMS. Required.
   */
  prepared_by: string;
  prepared_at: string;
  reviewed_by?: string | null;
  reviewed_at?: string | null;
  valid_from?: string | null;
  valid_until?: string | null;
  /**
   * All workers who have signed on / read & understood.
   */
  signatures?: {
    name: string;
    staff_id?: string | null;
    trade?: string | null;
    signed_at: string;
    signature_image_url?: string | null;
    device_id?: string | null;
    gps?: {
      lat?: number;
      lng?: number;
    } | null;
  }[];
  /**
   * References to supporting docs (drawings, MSDS, isolation procedure).
   */
  attachments?: {
    url?: string;
    filename?: string;
    kind?: "drawing" | "msds_sds" | "iso_procedure" | "photo" | "other";
  }[];
  status: "draft" | "active" | "expired" | "superseded" | "archived";
  /**
   * How the SWMS entered the system. Set automatically by the intake pipeline.
   */
  source?: "cards_mobile" | "import_spreadsheet" | "capture_pdf" | "capture_photo" | "capture_email" | "manual_entry";
  /**
   * If extracted via vision AI, the raw text recovered from the source document. Preserved for audit.
   */
  raw_extract?: string | null;
  imported_at?: string | null;
  imported_from?: string | null;
}
