// AUTO-GENERATED FROM schemas/toolbox-talk.schema.json. DO NOT EDIT.
// Generated by scripts/gen-types.mjs. Run `node scripts/gen-types.mjs` to refresh.
// Source of truth: schemas/toolbox-talk.schema.json — edit the JSON, regenerate.

/**
 * A toolbox talk: a short safety/operational briefing delivered to a crew, with attendance recorded. Captured by EQ Cards or imported from registers.
 */
export interface ToolboxTalk {
  talk_id: string;
  tenant_id: string;
  external_id?: string | null;
  site_id: string;
  /**
   * Short title of the toolbox talk.
   */
  topic: string;
  category?:
    | null
    | "safety"
    | "quality"
    | "environment"
    | "operations"
    | "induction"
    | "emergency_procedure"
    | "incident_review"
    | "tool_specific"
    | "other";
  /**
   * Body of the toolbox talk — the actual content delivered.
   */
  content?: string | null;
  /**
   * Bullet-point key messages for attendee summary.
   */
  key_messages?: string[];
  delivered_by: string;
  delivered_by_user_id?: string | null;
  delivered_at: string;
  duration_minutes?: number | null;
  /**
   * @minItems 1
   */
  attendees: [
    {
      name: string;
      staff_id?: string | null;
      /**
       * For subbies/visitors not in our staff register.
       */
      company?: string | null;
      signed_at?: string | null;
      signature_image_url?: string | null;
    },
    ...{
      name: string;
      staff_id?: string | null;
      /**
       * For subbies/visitors not in our staff register.
       */
      company?: string | null;
      signed_at?: string | null;
      signature_image_url?: string | null;
    }[]
  ];
  /**
   * Notes on questions/issues raised during the talk.
   */
  discussion_points?: string[];
  /**
   * Follow-up actions assigned during the talk.
   */
  actions?: {
    action: string;
    owner?: string | null;
    due_date?: string | null;
    status?: "open" | "in_progress" | "completed" | "cancelled";
  }[];
  attachments?: {
    url?: string;
    filename?: string;
    kind?: "photo" | "document" | "video" | "other";
  }[];
  gps?: {
    lat?: number;
    lng?: number;
  } | null;
  device_id?: string | null;
  /**
   * Workflow status. draft = captured, not reviewed. submitted = pending supervisor approval. approved = signed off. rejected = needs re-capture.
   */
  status?: "draft" | "submitted" | "approved" | "rejected";
  source?: "cards_mobile" | "import_spreadsheet" | "capture_pdf" | "capture_photo" | "manual_entry";
  raw_extract?: string | null;
  imported_at?: string | null;
  imported_from?: string | null;
}
