/**
 * Report typography tokens — single source of truth.
 *
 * Sourced from EQ Solutions Design Brief v1.3, §6.2:
 *
 *   Surface             Typeface          Role
 *   ----------------    --------------    -------------------------
 *   Web / UI            Plus Jakarta Sans All digital product surfaces
 *   Word / PowerPoint   Aptos Display     Headings and titles
 *   Word / PowerPoint   Aptos             Body copy
 *
 * Reports generated by this module are DOCX (Word) — so we use Aptos
 * Display for headings and Aptos for body. Aptos ships as the default
 * font in Microsoft 365 since 2024; on older Office or non-Microsoft
 * viewers Word substitutes automatically (typically to Calibri).
 *
 * The HTML→PDF templates (lib/reports/html/*) use Plus Jakarta Sans
 * via the web import — that's correct per §6.2 ("digital product
 * surfaces"). They do NOT import from this file.
 *
 * If a generator hardcodes a font name, that's a brief violation
 * (per the 2026-04-26 reports design audit, finding S1). Import
 * from here instead.
 */

/** Headings and titles in Word/DOCX outputs. Microsoft 365 default. */
export const FONT_HEADING = 'Aptos Display'

/** Body copy in Word/DOCX outputs. Microsoft 365 default. */
export const FONT_BODY = 'Aptos'
