/**
 * scripts/generate.ts - JSON Schema -> TypeScript types + Zod validators.
 *
 * Per Sprint 1 decisions #1, #8, #9:
 *   - JSON Schema is the single source of truth.
 *   - TypeScript and Zod are generated artifacts.
 *   - src/generated/ is gitignored; this script regenerates it.
 *
 * Invocation:
 *   pnpm --filter @eq/schemas generate
 *   (cwd is packages/eq-schemas/ when invoked via pnpm)
 */

import { readFile, writeFile, readdir, mkdir, rm } from "node:fs/promises";
import { join, resolve } from "node:path";
import { compile as compileTypes } from "json-schema-to-typescript";
import { jsonSchemaToZod } from "json-schema-to-zod";

const PKG_ROOT = resolve(process.cwd());
const SCHEMAS_DIR = join(PKG_ROOT, "src", "schemas");
const OUT_DIR = join(PKG_ROOT, "src", "generated");

const HEADER = (file: string) =>
  "// AUTO-GENERATED FROM " + file + ". DO NOT EDIT.\n" +
  "// Generated by scripts/generate.ts. Run `pnpm generate` to refresh.\n" +
  "// Source of truth lives in src/schemas/ - edit the JSON, regenerate.\n\n";

const INDEX_HEADER =
  "// AUTO-GENERATED. DO NOT EDIT.\n" +
  "// Re-exports every generated type and Zod validator. Regenerate via\n" +
  "// `pnpm generate`. Source of truth: src/schemas/*.schema.json.\n\n";

function pascalCase(s: string): string {
  return s
    .split(/[-_]/g)
    .map((part) => (part.length === 0 ? part : part[0]!.toUpperCase() + part.slice(1)))
    .join("");
}

function camelCase(s: string): string {
  const pc = pascalCase(s);
  return pc.length === 0 ? pc : pc[0]!.toLowerCase() + pc.slice(1);
}

async function main() {
  await rm(OUT_DIR, { recursive: true, force: true });
  await mkdir(OUT_DIR, { recursive: true });

  const all = await readdir(SCHEMAS_DIR);
  const files = all.filter((f) => f.endsWith(".schema.json")).sort();

  if (files.length === 0) {
    console.error("[generate] No *.schema.json files found in " + SCHEMAS_DIR);
    process.exit(1);
  }

  const reExports: string[] = [];

  for (const file of files) {
    const entity = file.replace(/\.schema\.json$/, "");
    const path = join(SCHEMAS_DIR, file);
    const raw = await readFile(path, "utf8");
    const json = JSON.parse(raw);

    // Derive a clean PascalCase identifier. The schema's `title` may contain
    // spaces ("Incident Report") which is good for humans but not a valid TS
    // identifier - we always normalise so the generated `export type Foo`
    // compiles cleanly.
    const typeName = pascalCase(entity);

    const typesSrc = await compileTypes(json, typeName, {
      bannerComment: HEADER(file).trimEnd(),
      additionalProperties: false,
      style: { semi: true, singleQuote: false, tabWidth: 2 },
      cwd: SCHEMAS_DIR,
      declareExternallyReferenced: true,
      enableConstEnums: false,
      strictIndexSignatures: false,
    });
    await writeFile(join(OUT_DIR, entity + ".types.ts"), typesSrc);

    const zodVarName = camelCase(entity) + "Schema";
    const zodSrc = jsonSchemaToZod(json, {
      name: zodVarName,
      module: "esm",
      type: typeName,
    });
    await writeFile(join(OUT_DIR, entity + ".zod.ts"), HEADER(file) + zodSrc);

    reExports.push('export type * from "./' + entity + '.types.js";');
    reExports.push("export { " + zodVarName + ' } from "./' + entity + '.zod.js";');

    console.log("[generate] " + file + " -> " + entity + ".types.ts + " + entity + ".zod.ts");
  }

  await writeFile(join(OUT_DIR, "index.ts"), INDEX_HEADER + reExports.join("\n") + "\n");
  console.log("[generate] Done. " + files.length + " schema modules -> " + OUT_DIR);
}

main().catch((err) => {
  console.error("[generate] FAILED");
  console.error(err);
  process.exit(1);
});
