-- ============================================================
-- Migration 0071: PM Calendar — draft / commit lifecycle
--
-- Replaces the original 0071 (pm_calendar_imports + import_rows staging
-- tables) with a much simpler model after the 2026-04-27 audit conversation
-- with Royce. Workflow facts that drove the simplification:
--
--   - Calendar carries over year to year with annual adjustments. Generator
--     creates next year's draft from contract_scopes + assets.next_due_per_cycle.
--     Supervisor reviews + adjusts in-app, never builds from scratch.
--
--   - Customer-returned feedback is verbal / email, not a marked-up xlsx.
--     No re-import path needed. xlsx is an EXPORT format only.
--
--   - Scope coverage gaps are tracked as defect-like "open items" in
--     scope_coverage_gaps (migration 0073), not by blocking commit.
--
-- So pm_calendar just needs an extra status field for the draft / committed
-- lifecycle. No staging tables. The generator writes pm_calendar entries
-- directly with draft_status='draft'; supervisor edits in-app; commit flips
-- to 'committed' which auto-runs the coverage check that populates
-- scope_coverage_gaps.
--
-- A one-time bootstrap utility (Python script, not in DB) imports an
-- existing customer's historical xlsx into pm_calendar with
-- draft_status='committed' so we have a starting point.
-- ============================================================

ALTER TABLE public.pm_calendar
  ADD COLUMN IF NOT EXISTS draft_status text NOT NULL DEFAULT 'committed'
    CHECK (draft_status IN ('draft', 'in_review', 'committed', 'cancelled'));

COMMENT ON COLUMN public.pm_calendar.draft_status IS
  'Lifecycle of the calendar entry from draft generation through to customer-approved commit. Distinct from .status which tracks delivery (scheduled/in_progress/completed/cancelled).
   draft     = generated by the year-ahead calendar generator, not yet ready for customer
   in_review = supervisor is actively editing / reviewing
   committed = supervisor signed off; can be sent to customer; coverage check populates scope_coverage_gaps
   cancelled = abandoned (replaced by a later draft, or the year wasn''t executed)';

-- Index for the supervisor's primary view: "show me everything not yet committed"
CREATE INDEX IF NOT EXISTS pm_calendar_draft_status_idx
  ON public.pm_calendar(tenant_id, draft_status)
  WHERE draft_status != 'committed';
-- pm_calendar has no customer_id column; customer is resolved via site_id -> sites.customer_id.

-- Existing rows default to 'committed' so legacy data validates.
