#!/usr/bin/env node
/**
 * scripts/gen-types.mjs — Generate TypeScript types from canonical schemas.
 *
 * Reads every *.schema.json from ../schemas/ and emits a matching .d.ts file
 * into ../types/. Uses json-schema-to-typescript resolved from the eq-platform
 * monorepo (no separate install needed).
 *
 * Usage:
 *   node scripts/gen-types.mjs
 *   (run from repo root or from inside scripts/)
 *
 * Source of truth: schemas/*.schema.json. Edit JSON, regenerate types.
 */
import { readFile, writeFile, readdir, mkdir, rm } from "node:fs/promises";
import { join, resolve, dirname } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { createRequire } from "node:module";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const REPO_ROOT = resolve(__dirname, "..");
const SCHEMAS_DIR = join(REPO_ROOT, "schemas");
const TYPES_DIR = join(REPO_ROOT, "types");
const EQ_PLATFORM = join(REPO_ROOT, "eq-platform");

// Resolve json-schema-to-typescript from the eq-platform monorepo so we
// don't need a separate top-level node_modules install.
const requireFromPlatform = createRequire(
  pathToFileURL(join(EQ_PLATFORM, "package.json")).href,
);
const jsts = requireFromPlatform("json-schema-to-typescript");
const compileTypes = jsts.compile;

function pascalCase(s) {
  return s
    .split(/[-_]/g)
    .map((part) => (part.length === 0 ? part : part[0].toUpperCase() + part.slice(1)))
    .join("");
}

const HEADER = (file) =>
  "// AUTO-GENERATED FROM schemas/" + file + ". DO NOT EDIT.\n" +
  "// Generated by scripts/gen-types.mjs. Run `node scripts/gen-types.mjs` to refresh.\n" +
  "// Source of truth: schemas/" + file + " — edit the JSON, regenerate.\n\n";

const INDEX_HEADER =
  "// AUTO-GENERATED. DO NOT EDIT.\n" +
  "// Re-exports every generated type. Regenerate via `node scripts/gen-types.mjs`.\n" +
  "// Source of truth: schemas/*.schema.json.\n\n";

async function main() {
  await rm(TYPES_DIR, { recursive: true, force: true });
  await mkdir(TYPES_DIR, { recursive: true });

  const all = await readdir(SCHEMAS_DIR);
  const files = all.filter((f) => f.endsWith(".schema.json")).sort();

  if (files.length === 0) {
    console.error("[gen-types] No *.schema.json files found in " + SCHEMAS_DIR);
    process.exit(1);
  }

  const reExports = [];

  for (const file of files) {
    const entity = file.replace(/\.schema\.json$/, "");
    const path = join(SCHEMAS_DIR, file);
    const raw = await readFile(path, "utf8");
    const json = JSON.parse(raw);

    const typeName = pascalCase(entity);

    const typesSrc = await compileTypes(json, typeName, {
      bannerComment: HEADER(file).trimEnd(),
      additionalProperties: false,
      style: { semi: true, singleQuote: false, tabWidth: 2 },
      cwd: SCHEMAS_DIR,
      declareExternallyReferenced: true,
      enableConstEnums: false,
      strictIndexSignatures: false,
    });
    await writeFile(join(TYPES_DIR, entity + ".d.ts"), typesSrc);

    reExports.push('export type * from "./' + entity + '.d.ts";');
    console.log("[gen-types] " + file + " -> types/" + entity + ".d.ts");
  }

  await writeFile(join(TYPES_DIR, "index.d.ts"), INDEX_HEADER + reExports.join("\n") + "\n");
  console.log("[gen-types] Done. " + files.length + " schema(s) -> " + TYPES_DIR);
}

main().catch((err) => {
  console.error("[gen-types] FAILED");
  console.error(err);
  process.exit(1);
});
